//! odyssey1e — Tauri commands.
//!
//! Every command here is a thin wrapper: pull the token out of state,
//! call one thing in `supabase`, hand the result back. Rules logic does
//! not belong in this file. When the dice roller lands it goes in its
//! own module with its own tests, and a command calls it.
//!
//! Commands are deliberately NOT async — Tauri runs sync commands on a
//! thread pool, so the blocking HTTP in `supabase` is fine here and the
//! code stays readable.

mod attack;
mod character;
mod dice;
mod encounter;
mod equipment;
mod narrative;
mod resolution;
mod supabase;

use character::{Resolved, Sheet};
use dice::{RandomRoller, RollResult};
use resolution::{Target, TargetKind};
use serde_json::{json, Value};
use supabase::{AppState, Session};
use tauri::State;

/* ============================ AUTH ============================ */

#[tauri::command]
fn sign_up(
    state: State<AppState>,
    email: String,
    password: String,
    display_name: String,
) -> Result<Session, String> {
    let s = supabase::sign_up(&email, &password, &display_name)?;
    state.set(Some(s.clone()))?;
    Ok(s)
}

#[tauri::command]
fn sign_in(state: State<AppState>, email: String, password: String) -> Result<Session, String> {
    let s = supabase::sign_in(&email, &password)?;
    state.set(Some(s.clone()))?;
    Ok(s)
}

#[tauri::command]
fn sign_out(state: State<AppState>) -> Result<(), String> {
    state.set(None)
}

/// Who am I, or null. Lets the frontend render without guessing.
#[tauri::command]
fn me(state: State<AppState>) -> Result<Option<Session>, String> {
    state.current()
}

/* ============================ GAMES ============================ */

/// Every game I am a member of. The DM sees theirs because the
/// on_game_created trigger seats them as a member; without it this
/// would return nothing for the person who made the game.
#[tauri::command]
fn list_games(state: State<AppState>) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "games",
        &[("select", "id,name,join_code,is_open,created_at"), ("order", "created_at.desc")],
    )
}

#[tauri::command]
fn create_game(state: State<AppState>, name: String) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;
    // join_code is generated by the column default; dm_uid must be us or
    // the insert policy rejects it.
    supabase::rest_insert(
        &session.access_token,
        "games",
        &json!({ "name": name, "dm_uid": session.user_id }),
    )
}

/// The only way into a game. See migration 001 — game_members has no
/// INSERT policy at all, on purpose.
#[tauri::command]
fn join_game(state: State<AppState>, code: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rpc(&token, "join_game", &json!({ "p_code": code }))
}

#[tauri::command]
fn list_members(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "game_members",
        &[
            ("select", "profile_id,role,joined_at"),
            ("game_id", &format!("eq.{}", game_id)),
        ],
    )
}

/* ============================ CHARACTERS ============================ */

#[tauri::command]
fn list_characters(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "characters",
        &[
            ("select", "id,name,token_name,owner_uid,is_active"),
            ("game_id", &format!("eq.{}", game_id)),
            ("order", "name.asc"),
        ],
    )
}

#[tauri::command]
fn create_character(
    state: State<AppState>,
    game_id: String,
    name: String,
    token_name: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;
    supabase::rest_insert(
        &session.access_token,
        "characters",
        &json!({
            "game_id": game_id,
            "owner_uid": session.user_id,
            "name": name,
            "token_name": token_name
        }),
    )
}

/* ============================ ROLLS ============================ */

#[tauri::command]
fn list_rolls(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "rolls",
        &[
            (
                "select",
                "id,created_at,character_name,roller_name,label,request,detail,total,\
                 natural_roll,status,narrative,\
                 target_value,target_kind,target_label,success,reason,margin,face_outcome",
            ),
            ("game_id", &format!("eq.{}", game_id)),
            ("order", "created_at.desc"),
            ("limit", "50"),
        ],
    )
}

/// Resolve a formula without touching the database. The engine is
/// deterministic given its dice, so this is also the fastest way to
/// eyeball a formula by hand.
#[tauri::command]
fn roll_dice(formula: String) -> Result<RollResult, String> {
    dice::roll_formula(&formula)
}

/// Insert a roll.
///
/// character_name and roller_name are left out on purpose — the
/// snapshot_roll_names() trigger fills them, so a client cannot forget
/// or fake them.
///
/// THE DICE ARE ROLLED HERE, ON THE DEVICE, before anything crosses the
/// network. That is the whole point of putting the engine in Rust: the
/// result exists the instant the player taps, and the insert is a
/// record of something that already happened rather than a request for
/// the server to make it happen.
///
/// No formula means no resolution — the row lands `pending` for
/// something else to finish. Named requests like "insight" will resolve
/// here too once the character sheet exists to supply the modifier.
#[tauri::command]
fn create_roll(
    state: State<AppState>,
    game_id: String,
    character_id: Option<String>,
    request: String,
    label: Option<String>,
    formula: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;

    let mut body = json!({
        "game_id": game_id,
        "character_id": character_id,
        "owner_uid": session.user_id,
        "request": request,
        "label": label,
        "status": "pending"
    });

    if let Some(f) = formula.as_deref().map(str::trim).filter(|f| !f.is_empty()) {
        // A bad formula fails before the insert, so a malformed roll
        // never reaches the log at all.
        let r = dice::roll_formula(f)?;
        body["formula"] = json!(f);
        body["detail"] = json!(r.detail);
        body["total"] = json!(r.total);
        body["natural_roll"] = json!(r.natural);
        body["status"] = json!("resolved");
    }

    supabase::rest_insert(&session.access_token, "rolls", &body)
}

/// The phase-two patch. Allowed only while the roll is pending or
/// resolved; the policy stops matching once it is delivered, which is
/// what makes the log trustworthy.
#[tauri::command]
fn patch_roll_narrative(
    state: State<AppState>,
    roll_id: String,
    narrative: String,
) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_update(
        &token,
        "rolls",
        &[("id", &format!("eq.{}", roll_id))],
        &json!({ "narrative": narrative }),
    )
}

/* ============================ CHARACTER SHEET ============================ */

/// Everything the resolver needs, in one call: level, six abilities, the
/// skill catalogue for this game, and which skills are proficient.
#[tauri::command]
fn get_sheet(state: State<AppState>, character_id: String) -> Result<Sheet, String> {
    let token = state.token()?;
    character::load_sheet(&token, &character_id)
}

#[tauri::command]
fn set_level(state: State<AppState>, character_id: String, level: i64) -> Result<Value, String> {
    if !(1..=20).contains(&level) {
        return Err("level must be 1-20".to_string());
    }
    let token = state.token()?;
    supabase::rest_update(
        &token,
        "characters",
        &[("id", &format!("eq.{}", character_id))],
        &json!({ "level": level }),
    )
}

/// Upsert one ability. The row always exists — the database seeds six on
/// character creation — so this is an update, not an insert.
#[tauri::command]
fn set_ability(
    state: State<AppState>,
    character_id: String,
    ability: String,
    score: i64,
    save_prof: bool,
) -> Result<Value, String> {
    if !(1..=30).contains(&score) {
        return Err("score must be 1-30".to_string());
    }
    let token = state.token()?;
    supabase::rest_update(
        &token,
        "character_abilities",
        &[
            ("character_id", &format!("eq.{}", character_id)),
            ("ability", &format!("eq.{}", ability)),
        ],
        &json!({ "score": score, "save_prof": save_prof }),
    )
}

/// Set a skill's proficiency multiplier. Zero deletes the row rather
/// than storing it: an absent row already means untrained, and keeping
/// both representations of the same fact invites them to disagree.
#[tauri::command]
fn set_skill_prof(
    state: State<AppState>,
    character_id: String,
    skill_key: String,
    prof: f64,
) -> Result<Value, String> {
    if ![0.0, 0.5, 1.0, 2.0].contains(&prof) {
        return Err("prof must be 0, 0.5, 1 or 2".to_string());
    }
    let token = state.token()?;
    let filter = [
        ("character_id", format!("eq.{}", character_id)),
        ("skill_key", format!("eq.{}", skill_key)),
    ];
    let filter: Vec<(&str, &str)> =
        filter.iter().map(|(k, v)| (*k, v.as_str())).collect();

    if prof == 0.0 {
        supabase::rest_delete(&token, "character_skills", &filter)?;
        return Ok(json!([]));
    }

    supabase::rest_upsert(
        &token,
        "character_skills",
        &json!({ "character_id": character_id, "skill_key": skill_key, "prof": prof }),
        "character_id,skill_key",
    )
}

/* ============================ EQUIPMENT ============================ */

/// Everything this character owns, equipped or not, with proficiency and
/// attack modes already derived.
///
/// Separate from the sheet's `loadout` on purpose. The sheet carries what
/// is EQUIPPED, because that is all an attack can depend on and the sheet
/// is read on every roll. A screen wants the whole list, and pays three
/// queries for it rather than the seven load_sheet costs.
#[tauri::command]
fn list_inventory(
    state: State<AppState>,
    character_id: String,
) -> Result<Vec<equipment::Owned>, String> {
    let token = state.token()?;
    let p = character::load_profile(&token, &character_id)?;
    equipment::load_loadout(
        &token,
        &character_id,
        &p.game_id,
        &p.weapon_profs,
        &p.armor_profs,
        false,
    )
}

/// Equip or unequip one item.
///
/// This exists so the one-armor rule is ENFORCED rather than merely
/// described. `character_items.equipped` is deliberately unconstrained —
/// several weapons may be held at once — and the one-armor rule cannot
/// live in a partial index because deciding it needs `items.kind` from
/// another table. 008's comment says the rule lives in equipment.rs, and
/// a rule that only runs on the way out is a lint, not a rule.
///
/// The check reads the loadout as it would be AFTER the change, so it
/// refuses the second breastplate instead of reporting it afterwards.
#[tauri::command]
fn set_item_equipped(
    state: State<AppState>,
    character_id: String,
    item_key: String,
    equipped: bool,
) -> Result<Value, String> {
    let token = state.token()?;

    if equipped {
        let sheet = character::load_sheet(&token, &character_id)?;
        let incoming = equipment::load_item(&token, &sheet.game_id, &item_key)?
            .ok_or_else(|| format!("no item with key '{}'", item_key))?;

        // Only an armor can break the rule, so nothing else pays for
        // the check. Re-equipping something already worn is not a
        // second armor, hence filtering the incoming key out first.
        if incoming.kind == "armor" {
            let mut after: Vec<&equipment::Item> = sheet
                .loadout
                .iter()
                .map(|e| &e.item)
                .filter(|i| i.key != item_key)
                .collect();
            after.push(&incoming);
            equipment::check_one_armor(&after)?;
        }
    }

    supabase::rest_upsert(
        &token,
        "character_items",
        &json!({
            "character_id": character_id,
            "item_key": item_key,
            "equipped": equipped
        }),
        "character_id,item_key",
    )
}

/// Every `techniques.item_key` that resolves to no item.
///
/// There is no FK behind that reference and there cannot be — a partial
/// unique index cannot back one — so this is the only thing that will
/// ever notice a typo. An empty list is the passing answer.
#[tauri::command]
fn check_item_keys(state: State<AppState>, game_id: String) -> Result<Vec<String>, String> {
    let token = state.token()?;
    equipment::check_item_keys(&token, &game_id)
}

/* ============================ NAMED ROLLS ============================ */

/// What would this request roll, and why — without rolling it. Lets a UI
/// show "Insight (WIS) +6" on the button before anyone commits.
#[tauri::command]
fn preview_request(
    state: State<AppState>,
    character_id: String,
    request: String,
    mode: String,
) -> Result<Resolved, String> {
    let token = state.token()?;
    let sheet = character::load_sheet(&token, &character_id)?;
    Ok(character::resolve_request(&sheet, &request, &mode))
}

/// The whole path: read the sheet, resolve the request into a formula,
/// roll it here on the device, pick the line that narrates it, and log
/// the finished result.
///
/// The insert records something that already happened. Nothing about the
/// outcome depends on the network — if the write fails, the dice were
/// still fair, and the row is the only thing lost.
///
/// The narrative goes in with the dice rather than being patched on
/// afterwards, and that does not contradict "never let a slow optional
/// enrichment gate a fast required result": a canned line is neither
/// slow nor remote. The pack came down with the sheet, so choosing one
/// is a local die roll. The patch path stays for the AI-written
/// narrative, which is the enrichment that rule is actually about.
#[tauri::command]
fn roll_named(
    state: State<AppState>,
    character_id: String,
    request: String,
    mode: String,
    target_value: Option<i64>,
    target_kind: Option<String>,
    target_label: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;

    // Refused before any dice are thrown: a half-supplied target is a
    // caller bug, and rolling first would leave a resolved row that
    // cannot record what it was for.
    let target = parse_target(target_value, target_kind, target_label)?;

    let sheet = character::load_sheet(&session.access_token, &character_id)?;
    let resolved = character::resolve_request(&sheet, &request, &mode);

    // A technique brings its own crit and fumble range; everything else
    // uses 20 and 1. Thresholds::new refuses a pair whose ranges meet,
    // so a bad technique row fails here rather than deciding a roll.
    let thresholds = match &resolved.attack {
        Some(a) => dice::Thresholds::new(a.crit_min, a.fumble_max)?,
        None => dice::Thresholds::STANDARD,
    };
    let rolled = dice::roll_formula_as(&resolved.formula, thresholds)?;
    // None for a key no pack has written yet. The column is nullable and
    // the card reads fine without prose, so that is not an error.
    let line = narrative::pick(&sheet.narratives, &resolved.key, &mut RandomRoller);

    let mut body = json!({
        "game_id": sheet.game_id,
        "character_id": sheet.character_id,
        "owner_uid": session.user_id,
        "request": request,
        "label": resolved.label,
        "mode": mode,
        "formula": resolved.formula,
        "detail": rolled.detail,
        "total": rolled.total,
        "natural_roll": rolled.natural,
        "face_outcome": rolled.outcome,
        "narrative": line,
        "status": "resolved"
    });

    // The thresholds go on the row only when a face was actually judged,
    // matching the column comments: null means no d20, not 20 and 1.
    if rolled.natural.is_some() {
        body["crit_min"] = json!(thresholds.crit_min);
        body["fumble_max"] = json!(thresholds.fumble_max);
    }

    if let Some(t) = &target {
        let verdict = resolution::resolve(rolled.total, rolled.outcome, t);
        body["target_value"] = json!(t.value);
        body["target_kind"] = json!(t.kind.as_str());
        body["target_label"] = json!(t.label);
        body["success"] = json!(verdict.success);
        body["reason"] = json!(verdict.reason.as_str());
        body["margin"] = json!(verdict.margin);
    }

    supabase::rest_insert(&session.access_token, "rolls", &body)
}

/// Both target inputs or neither.
///
/// A value with no kind cannot be resolved - the auto-hit rule needs to
/// know whether it is an AC or a DC - and silently treating it as one or
/// the other would decide a roll on a guess. Half a target is refused
/// rather than defaulted.
fn parse_target(
    value: Option<i64>,
    kind: Option<String>,
    label: Option<String>,
) -> Result<Option<Target>, String> {
    match (value, kind.as_deref().map(str::trim).filter(|k| !k.is_empty())) {
        (None, None) => Ok(None),
        (Some(v), Some(k)) => {
            let kind = TargetKind::parse(k)
                .ok_or_else(|| format!("target kind must be ac or dc, got \"{}\"", k))?;
            Ok(Some(Target {
                value: v,
                kind,
                label: label
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty()),
            }))
        }
        (Some(_), None) => Err("a target value needs a kind: ac or dc".to_string()),
        (None, Some(_)) => Err("a target kind needs a value to beat".to_string()),
    }
}

/* ============================ ENCOUNTERS ============================ */

/// The encounters in a game, newest first. `active` is the one in front
/// of the table; at most one per game, enforced by a partial unique
/// index rather than by hope.
#[tauri::command]
fn list_encounters(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "encounters",
        &[
            ("select", "id,name,status,created_at"),
            ("game_id", &format!("eq.{}", game_id)),
            ("order", "created_at.desc"),
        ],
    )
}

/// Everything in an encounter a roll can be aimed at: actors with their
/// resolved AC, challenges with their DC, in one list.
///
/// The AC is worked out per actor rather than read off a column - see
/// encounter.rs. A character's is computed from what they are wearing by
/// the same function their own sheet uses, so the DM's target list and
/// the player's sheet cannot disagree about what it takes to hit them.
#[tauri::command]
fn list_targets(
    state: State<AppState>,
    encounter_id: String,
) -> Result<Vec<encounter::Target>, String> {
    let token = state.token()?;
    encounter::load_targets(&token, &encounter_id)
}

/* ============================ ENTRY ============================ */

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .manage(AppState::default())
        .invoke_handler(tauri::generate_handler![
            sign_up,
            sign_in,
            sign_out,
            me,
            list_games,
            create_game,
            join_game,
            list_members,
            list_characters,
            create_character,
            list_rolls,
            list_encounters,
            list_targets,
            get_sheet,
            set_level,
            set_ability,
            set_skill_prof,
            list_inventory,
            set_item_equipped,
            check_item_keys,
            preview_request,
            roll_named,
            roll_dice,
            create_roll,
            patch_roll_narrative,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
