//! odyssey1e — Tauri commands.
//!
//! Every command here is a thin wrapper: pull the token out of state,
//! call one thing in `supabase`, hand the result back. Rules logic does
//! not belong in this file. When the dice roller lands it goes in its
//! own module with its own tests, and a command calls it.
//!
//! Commands are deliberately NOT async — Tauri runs sync commands on a
//! thread pool, so the blocking HTTP in `supabase` is fine here and the
//! code stays readable.

mod dice;
mod supabase;

use dice::RollResult;
use serde_json::{json, Value};
use supabase::{AppState, Session};
use tauri::State;

/* ============================ AUTH ============================ */

#[tauri::command]
fn sign_up(
    state: State<AppState>,
    email: String,
    password: String,
    display_name: String,
) -> Result<Session, String> {
    let s = supabase::sign_up(&email, &password, &display_name)?;
    state.set(Some(s.clone()))?;
    Ok(s)
}

#[tauri::command]
fn sign_in(state: State<AppState>, email: String, password: String) -> Result<Session, String> {
    let s = supabase::sign_in(&email, &password)?;
    state.set(Some(s.clone()))?;
    Ok(s)
}

#[tauri::command]
fn sign_out(state: State<AppState>) -> Result<(), String> {
    state.set(None)
}

/// Who am I, or null. Lets the frontend render without guessing.
#[tauri::command]
fn me(state: State<AppState>) -> Result<Option<Session>, String> {
    state.current()
}

/* ============================ GAMES ============================ */

/// Every game I am a member of. The DM sees theirs because the
/// on_game_created trigger seats them as a member; without it this
/// would return nothing for the person who made the game.
#[tauri::command]
fn list_games(state: State<AppState>) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "games",
        &[("select", "id,name,join_code,is_open,created_at"), ("order", "created_at.desc")],
    )
}

#[tauri::command]
fn create_game(state: State<AppState>, name: String) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;
    // join_code is generated by the column default; dm_uid must be us or
    // the insert policy rejects it.
    supabase::rest_insert(
        &session.access_token,
        "games",
        &json!({ "name": name, "dm_uid": session.user_id }),
    )
}

/// The only way into a game. See migration 001 — game_members has no
/// INSERT policy at all, on purpose.
#[tauri::command]
fn join_game(state: State<AppState>, code: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rpc(&token, "join_game", &json!({ "p_code": code }))
}

#[tauri::command]
fn list_members(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "game_members",
        &[
            ("select", "profile_id,role,joined_at"),
            ("game_id", &format!("eq.{}", game_id)),
        ],
    )
}

/* ============================ CHARACTERS ============================ */

#[tauri::command]
fn list_characters(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "characters",
        &[
            ("select", "id,name,token_name,owner_uid,is_active"),
            ("game_id", &format!("eq.{}", game_id)),
            ("order", "name.asc"),
        ],
    )
}

#[tauri::command]
fn create_character(
    state: State<AppState>,
    game_id: String,
    name: String,
    token_name: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;
    supabase::rest_insert(
        &session.access_token,
        "characters",
        &json!({
            "game_id": game_id,
            "owner_uid": session.user_id,
            "name": name,
            "token_name": token_name
        }),
    )
}

/* ============================ ROLLS ============================ */

#[tauri::command]
fn list_rolls(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "rolls",
        &[
            (
                "select",
                "id,created_at,character_name,roller_name,label,request,detail,total,natural_roll,status,narrative",
            ),
            ("game_id", &format!("eq.{}", game_id)),
            ("order", "created_at.desc"),
            ("limit", "50"),
        ],
    )
}

/// Resolve a formula without touching the database. The engine is
/// deterministic given its dice, so this is also the fastest way to
/// eyeball a formula by hand.
#[tauri::command]
fn roll_dice(formula: String) -> Result<RollResult, String> {
    dice::roll_formula(&formula)
}

/// Insert a roll.
///
/// character_name and roller_name are left out on purpose — the
/// snapshot_roll_names() trigger fills them, so a client cannot forget
/// or fake them.
///
/// THE DICE ARE ROLLED HERE, ON THE DEVICE, before anything crosses the
/// network. That is the whole point of putting the engine in Rust: the
/// result exists the instant the player taps, and the insert is a
/// record of something that already happened rather than a request for
/// the server to make it happen.
///
/// No formula means no resolution — the row lands `pending` for
/// something else to finish. Named requests like "insight" will resolve
/// here too once the character sheet exists to supply the modifier.
#[tauri::command]
fn create_roll(
    state: State<AppState>,
    game_id: String,
    character_id: Option<String>,
    request: String,
    label: Option<String>,
    formula: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;

    let mut body = json!({
        "game_id": game_id,
        "character_id": character_id,
        "owner_uid": session.user_id,
        "request": request,
        "label": label,
        "status": "pending"
    });

    if let Some(f) = formula.as_deref().map(str::trim).filter(|f| !f.is_empty()) {
        // A bad formula fails before the insert, so a malformed roll
        // never reaches the log at all.
        let r = dice::roll_formula(f)?;
        body["formula"] = json!(f);
        body["detail"] = json!(r.detail);
        body["total"] = json!(r.total);
        body["natural_roll"] = json!(r.natural);
        body["status"] = json!("resolved");
    }

    supabase::rest_insert(&session.access_token, "rolls", &body)
}

/// The phase-two patch. Allowed only while the roll is pending or
/// resolved; the policy stops matching once it is delivered, which is
/// what makes the log trustworthy.
#[tauri::command]
fn patch_roll_narrative(
    state: State<AppState>,
    roll_id: String,
    narrative: String,
) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_update(
        &token,
        "rolls",
        &[("id", &format!("eq.{}", roll_id))],
        &json!({ "narrative": narrative }),
    )
}

/* ============================ ENTRY ============================ */

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .manage(AppState::default())
        .invoke_handler(tauri::generate_handler![
            sign_up,
            sign_in,
            sign_out,
            me,
            list_games,
            create_game,
            join_game,
            list_members,
            list_characters,
            create_character,
            list_rolls,
            roll_dice,
            create_roll,
            patch_roll_narrative,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
