//! odyssey1e — Tauri commands.
//!
//! Every command here is a thin wrapper: pull the token out of state,
//! call one thing in `supabase`, hand the result back. Rules logic does
//! not belong in this file. When the dice roller lands it goes in its
//! own module with its own tests, and a command calls it.
//!
//! Commands are deliberately NOT async — Tauri runs sync commands on a
//! thread pool, so the blocking HTTP in `supabase` is fine here and the
//! code stays readable.
//!
//! THIS FILE IS BEING BRANCHED. Both statements above are still true and
//! the file is 944 lines anyway, because "thin" describes each command
//! and not how many of them belong together. `commands/` is where the
//! surface is moving; `commands/mod.rs` carries the map of which group
//! goes where and in what order, and it is the thing to read before
//! adding to this file. New material goes there rather than here.
//!
//! What stays: `run()` and the `generate_handler!` list. One registry in
//! the crate root is what you read to find out what the app can do.

mod attack;
mod character;
mod commands;
mod death;
mod dice;
mod encounter;
mod equipment;
mod narrative;
mod objects;
mod pin;
mod resolution;
mod supabase;

use character::{Resolved, Sheet};
use dice::{RandomRoller, RollResult};
use resolution::{Target, TargetKind};
use serde_json::{json, Value};
use supabase::{AppState, Session};
use tauri::State;

/* ============================ AUTH ============================ */

#[tauri::command]
fn sign_up(
    state: State<AppState>,
    email: String,
    password: String,
    display_name: String,
) -> Result<Session, String> {
    let s = supabase::sign_up(&email, &password, &display_name)?;
    state.set(Some(s.clone()))?;
    Ok(s)
}

#[tauri::command]
fn sign_in(state: State<AppState>, email: String, password: String) -> Result<Session, String> {
    let s = supabase::sign_in(&email, &password)?;
    state.set(Some(s.clone()))?;
    Ok(s)
}

#[tauri::command]
fn sign_out(state: State<AppState>) -> Result<(), String> {
    state.set(None)
}

// `me` now lives in commands/session.rs. It moved on its own, as the
// exemplar for the branch described at the top of this file.

/* ============================ GAMES ============================ */

/// Every game I am a member of. The DM sees theirs because the
/// on_game_created trigger seats them as a member; without it this
/// would return nothing for the person who made the game.
#[tauri::command]
fn list_games(state: State<AppState>) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "games",
        // dm_uid so the frontend can tell whether to offer the DM side.
        // Not an access check — 011's policies are the access check, and
        // this only decides whether to show a panel that would refuse.
        &[
            ("select", "id,name,join_code,is_open,dm_uid,created_at"),
            ("order", "created_at.desc"),
        ],
    )
}

#[tauri::command]
fn create_game(state: State<AppState>, name: String) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;
    // join_code is generated by the column default; dm_uid must be us or
    // the insert policy rejects it.
    supabase::rest_insert(
        &session.access_token,
        "games",
        &json!({ "name": name, "dm_uid": session.user_id }),
    )
}

/// The only way into a game. See migration 001 — game_members has no
/// INSERT policy at all, on purpose.
#[tauri::command]
fn join_game(state: State<AppState>, code: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rpc(&token, "join_game", &json!({ "p_code": code }))
}

#[tauri::command]
fn list_members(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "game_members",
        &[
            ("select", "profile_id,role,joined_at"),
            ("game_id", &format!("eq.{}", game_id)),
        ],
    )
}

/* ============================ CHARACTERS ============================ */

#[tauri::command]
fn list_characters(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "characters",
        &[
            ("select", "id,name,token_name,owner_uid,is_active"),
            ("game_id", &format!("eq.{}", game_id)),
            // PEOPLE ONLY. Since 022 a monster is a character too, and
            // without this a player's list fills with goblins. is_npc is
            // a label rather than a structure - it changes no rule, it
            // decides which list you are looking at.
            ("is_npc", "is.false"),
            ("order", "name.asc"),
        ],
    )
}

#[tauri::command]
fn create_character(
    state: State<AppState>,
    game_id: String,
    name: String,
    token_name: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;
    supabase::rest_insert(
        &session.access_token,
        "characters",
        &json!({
            "game_id": game_id,
            "owner_uid": session.user_id,
            "name": name,
            "token_name": token_name
        }),
    )
}

/* ============================ ROLLS ============================ */

#[tauri::command]
fn list_rolls(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "rolls",
        &[
            (
                "select",
                "id,created_at,character_name,roller_name,label,request,detail,total,\
                 natural_roll,status,narrative,\
                 target_value,target_kind,target_label,success,reason,margin,face_outcome,                 action_id,role",
            ),
            ("game_id", &format!("eq.{}", game_id)),
            ("order", "created_at.desc"),
            ("limit", "50"),
        ],
    )
}

/// Resolve a formula without touching the database. The engine is
/// deterministic given its dice, so this is also the fastest way to
/// eyeball a formula by hand.
#[tauri::command]
fn roll_dice(formula: String) -> Result<RollResult, String> {
    dice::roll_formula(&formula)
}

/// Insert a roll.
///
/// character_name and roller_name are left out on purpose — the
/// snapshot_roll_names() trigger fills them, so a client cannot forget
/// or fake them.
///
/// THE DICE ARE ROLLED HERE, ON THE DEVICE, before anything crosses the
/// network. That is the whole point of putting the engine in Rust: the
/// result exists the instant the player taps, and the insert is a
/// record of something that already happened rather than a request for
/// the server to make it happen.
///
/// No formula means no resolution — the row lands `pending` for
/// something else to finish. Named requests like "insight" will resolve
/// here too once the character sheet exists to supply the modifier.
#[tauri::command]
fn create_roll(
    state: State<AppState>,
    game_id: String,
    character_id: Option<String>,
    request: String,
    label: Option<String>,
    formula: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;

    let mut body = json!({
        "game_id": game_id,
        "character_id": character_id,
        "owner_uid": session.user_id,
        "request": request,
        "label": label,
        "status": "pending"
    });

    if let Some(f) = formula.as_deref().map(str::trim).filter(|f| !f.is_empty()) {
        // A bad formula fails before the insert, so a malformed roll
        // never reaches the log at all.
        let r = dice::roll_formula(f)?;
        body["formula"] = json!(f);
        body["detail"] = json!(r.detail);
        body["total"] = json!(r.total);
        body["natural_roll"] = json!(r.natural);
        body["status"] = json!("resolved");
    }

    supabase::rest_insert(&session.access_token, "rolls", &body)
}

/// The phase-two patch. Allowed only while the roll is pending or
/// resolved; the policy stops matching once it is delivered, which is
/// what makes the log trustworthy.
#[tauri::command]
fn patch_roll_narrative(
    state: State<AppState>,
    roll_id: String,
    narrative: String,
) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_update(
        &token,
        "rolls",
        &[("id", &format!("eq.{}", roll_id))],
        &json!({ "narrative": narrative }),
    )
}

/* ============================ CHARACTER SHEET ============================ */

/// Everything the resolver needs, in one call: level, six abilities, the
/// skill catalogue for this game, and which skills are proficient.
#[tauri::command]
fn get_sheet(state: State<AppState>, character_id: String) -> Result<Sheet, String> {
    let token = state.token()?;
    character::load_sheet(&token, &character_id)
}

#[tauri::command]
fn set_level(state: State<AppState>, character_id: String, level: i64) -> Result<Value, String> {
    if !(1..=20).contains(&level) {
        return Err("level must be 1-20".to_string());
    }
    let token = state.token()?;
    supabase::rest_update(
        &token,
        "characters",
        &[("id", &format!("eq.{}", character_id))],
        &json!({ "level": level }),
    )
}

/// Upsert one ability. The row always exists — the database seeds six on
/// character creation — so this is an update, not an insert.
#[tauri::command]
fn set_ability(
    state: State<AppState>,
    character_id: String,
    ability: String,
    score: i64,
    save_prof: bool,
) -> Result<Value, String> {
    if !(1..=30).contains(&score) {
        return Err("score must be 1-30".to_string());
    }
    let token = state.token()?;
    supabase::rest_update(
        &token,
        "character_abilities",
        &[
            ("character_id", &format!("eq.{}", character_id)),
            ("ability", &format!("eq.{}", ability)),
        ],
        &json!({ "score": score, "save_prof": save_prof }),
    )
}

/// Set a skill's proficiency multiplier. Zero deletes the row rather
/// than storing it: an absent row already means untrained, and keeping
/// both representations of the same fact invites them to disagree.
#[tauri::command]
fn set_skill_prof(
    state: State<AppState>,
    character_id: String,
    skill_key: String,
    prof: f64,
) -> Result<Value, String> {
    if ![0.0, 0.5, 1.0, 2.0].contains(&prof) {
        return Err("prof must be 0, 0.5, 1 or 2".to_string());
    }
    let token = state.token()?;
    let filter = [
        ("character_id", format!("eq.{}", character_id)),
        ("skill_key", format!("eq.{}", skill_key)),
    ];
    let filter: Vec<(&str, &str)> =
        filter.iter().map(|(k, v)| (*k, v.as_str())).collect();

    if prof == 0.0 {
        supabase::rest_delete(&token, "character_skills", &filter)?;
        return Ok(json!([]));
    }

    supabase::rest_upsert(
        &token,
        "character_skills",
        &json!({ "character_id": character_id, "skill_key": skill_key, "prof": prof }),
        "character_id,skill_key",
    )
}

/* ============================ EQUIPMENT ============================ */

/// Everything this character owns, equipped or not, with proficiency and
/// attack modes already derived.
///
/// Separate from the sheet's `loadout` on purpose. The sheet carries what
/// is EQUIPPED, because that is all an attack can depend on and the sheet
/// is read on every roll. A screen wants the whole list, and pays three
/// queries for it rather than the seven load_sheet costs.
#[tauri::command]
fn list_inventory(
    state: State<AppState>,
    character_id: String,
) -> Result<Vec<equipment::Owned>, String> {
    let token = state.token()?;
    let p = character::load_profile(&token, &character_id)?;
    equipment::load_loadout(
        &token,
        &character_id,
        &p.game_id,
        &p.weapon_profs,
        &p.armor_profs,
        false,
    )
}

/// Equip or unequip one object.
///
/// This exists so the one-armor rule is ENFORCED rather than merely
/// described. `objects.equipped` is deliberately unconstrained -
/// several weapons may be held at once - and the one-armor rule cannot
/// live in a partial index because deciding it needs `items.kind` from
/// another table. 008's comment says the rule lives in equipment.rs, and
/// a rule that only runs on the way out is a lint, not a rule.
///
/// The check reads the loadout as it would be AFTER the change, so it
/// refuses the second breastplate instead of reporting it afterwards.
///
/// TAKES AN OBJECT, NOT A PAIR. Until 026 this was (character, item_key)
/// upserted on that pair, which had two faults the identity fixes. It
/// could CREATE inventory by accident - an upsert on a key that was not
/// there inserts - and after 026 that key is not even unique, because a
/// character may hold two shortswords. An id names one of them.
#[tauri::command]
fn set_item_equipped(
    state: State<AppState>,
    object_id: String,
    equipped: bool,
) -> Result<Value, String> {
    let token = state.token()?;

    if equipped {
        let obj = objects::load_object(&token, &object_id)?;
        let character_id = obj
            .character_id
            .ok_or_else(|| "nobody is holding that - it cannot be equipped".to_string())?;
        let sheet = character::load_sheet(&token, &character_id)?;
        let incoming = equipment::load_item(&token, &sheet.game_id, &obj.item_key)?
            .ok_or_else(|| format!("no item with key '{}'", obj.item_key))?;

        // Only an armor can break the rule, so nothing else pays for
        // the check. Filtering THIS object out first means re-equipping
        // what is already worn is not read as a second armor - and it
        // filters the object, not the key, because since 026 the other
        // breastplate is a different thing rather than the same row.
        if incoming.kind == "armor" {
            let mut after: Vec<&equipment::Item> = sheet
                .loadout
                .iter()
                .filter(|e| e.id != object_id)
                .map(|e| &e.item)
                .collect();
            after.push(&incoming);
            equipment::check_one_armor(&after)?;
        }
    }

    supabase::rest_update(
        &token,
        "objects",
        &[("id", &format!("eq.{}", object_id))],
        &json!({ "equipped": equipped }),
    )
}

/// Every `techniques.item_key` that resolves to no item.
///
/// There is no FK behind that reference and there cannot be — a partial
/// unique index cannot back one — so this is the only thing that will
/// ever notice a typo. An empty list is the passing answer.
#[tauri::command]
fn check_item_keys(state: State<AppState>, game_id: String) -> Result<Vec<String>, String> {
    let token = state.token()?;
    equipment::check_item_keys(&token, &game_id)
}

/* ============================ NAMED ROLLS ============================ */

/// What would this request roll, and why — without rolling it. Lets a UI
/// show "Insight (WIS) +6" on the button before anyone commits.
#[tauri::command]
fn preview_request(
    state: State<AppState>,
    character_id: String,
    request: String,
    mode: String,
) -> Result<Resolved, String> {
    let token = state.token()?;
    let sheet = character::load_sheet(&token, &character_id)?;
    Ok(character::resolve_request(&sheet, &request, &mode))
}

/// The whole path: read the sheet, resolve the request into a formula,
/// roll it here on the device, pick the line that narrates it, and log
/// the finished result.
///
/// The insert records something that already happened. Nothing about the
/// outcome depends on the network — if the write fails, the dice were
/// still fair, and the row is the only thing lost.
///
/// The narrative goes in with the dice rather than being patched on
/// afterwards, and that does not contradict "never let a slow optional
/// enrichment gate a fast required result": a canned line is neither
/// slow nor remote. The pack came down with the sheet, so choosing one
/// is a local die roll. The patch path stays for the AI-written
/// narrative, which is the enrichment that rule is actually about.
#[tauri::command]
fn roll_named(
    state: State<AppState>,
    character_id: String,
    request: String,
    mode: String,
    target_value: Option<i64>,
    target_kind: Option<String>,
    target_label: Option<String>,
    encounter_id: Option<String>,
    // The link half of the target, beside the snapshot half above. See
    // 013: the snapshot is the record and never changes, this is how the
    // thing to take hit points off gets found.
    target_id: Option<String>,
    target_row: Option<String>,
    target_character_id: Option<String>,
    // WHO SWUNG, as a participant. Not the same question as which sheet
    // it was, and what an experience system would eventually count.
    actor_id: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;
    let sheet = character::load_sheet(&session.access_token, &character_id)?;
    swing(
        &session,
        &sheet,
        Swing {
            request,
            mode,
            target_value,
            target_kind,
            target_label,
            encounter_id,
            target_id,
            target_row,
            target_character_id,
            actor_id,
        },
    )
}

/// What a swing is aimed at and under what conditions — everything that
/// varies between one roll and the next, once the sheet is known.
///
/// A struct rather than ten more arguments, because `swing` is the one
/// place a character and a monster meet and it should be readable at the
/// call site from either side.
pub(crate) struct Swing {
    pub request: String,
    pub mode: String,
    pub target_value: Option<i64>,
    pub target_kind: Option<String>,
    pub target_label: Option<String>,
    pub encounter_id: Option<String>,
    pub target_id: Option<String>,
    pub target_row: Option<String>,
    pub target_character_id: Option<String>,
    pub actor_id: Option<String>,
}

/// ONE ATTACK PATH, for whoever is holding the weapon.
///
/// This was the back half of `roll_named` and is now reachable with any
/// sheet, which is what lets a goblin swing without a second
/// implementation. 019 took the heavier of the two options for NPC
/// attacks precisely so this function would not have to grow a monster
/// branch: a statblock arrives here with scores, a proficiency bonus and
/// a loadout, exactly as a character does, and every rule below applies
/// without knowing which it got.
///
/// The only thing that differs is `sheet.character_id`, which is None
/// for a monster — see `roll_row`.
pub(crate) fn swing(session: &Session, sheet: &Sheet, s: Swing) -> Result<Value, String> {
    let Swing {
        request,
        mode,
        target_value,
        target_kind,
        target_label,
        encounter_id,
        target_id,
        target_row,
        target_character_id,
        actor_id,
    } = s;

    // Refused before any dice are thrown: a half-supplied target is a
    // caller bug, and rolling first would leave a resolved row that
    // cannot record what it was for.
    let target = parse_target(target_value, target_kind, target_label)?;

    let resolved = character::resolve_request(sheet, &request, &mode);

    // A technique brings its own crit and fumble range; everything else
    // uses 20 and 1. Thresholds::new refuses a pair whose ranges meet,
    // so a bad technique row fails here rather than deciding a roll.
    let thresholds = match &resolved.attack {
        Some(a) => dice::Thresholds::new(a.crit_min, a.fumble_max)?,
        None => dice::Thresholds::STANDARD,
    };

    // THE WHOLE SWING RESOLVES HERE, before anything crosses the
    // network. To-hit, the verdict, and the damage it earned are all
    // worked out on the device, so the write below records something
    // that already happened rather than asking for it to happen.
    let first = dice::roll_formula_as(&resolved.formula, thresholds)?;
    let verdict = target
        .as_ref()
        .map(|t| resolution::resolve(first.total, first.outcome, t));
    let line = narrative::pick(&sheet.narratives, &resolved.key, &mut RandomRoller);

    // Set by the damage branch below, and the signal that anything has
    // hit points to lose.
    let mut damage_total: Option<i64> = None;

    let role = if resolved.attack.is_some() { "to_hit" } else { "check" };
    let mut rolls = vec![roll_row(
        sheet,
        session,
        &request,
        &resolved.label,
        &mode,
        &resolved.formula,
        &first,
        Some(thresholds),
        line,
        target.as_ref(),
        verdict.as_ref(),
        role,
    )];

    // Damage, when the swing earned one. A crit doubles the DICE and
    // leaves the modifier alone — 1d6+1 becomes 2d6+1, never 2d6+2.
    if let Some(a) = &resolved.attack {
        if attack::rolls_damage(verdict.as_ref().map(|v| v.success)) {
            let crit = first.outcome == Some(dice::Outcome::Crit);
            let formula = if crit {
                dice::double_dice(&a.damage)?
            } else {
                a.damage.clone()
            };
            let rolled = dice::roll_formula(&formula)?;
            damage_total = Some(rolled.total);
            let label = if crit {
                format!("{} damage (crit)", a.weapon_name)
            } else {
                format!("{} damage", a.weapon_name)
            };
            rolls.push(roll_row(
                sheet,
                session,
                &request,
                &label,
                "normal",
                &formula,
                &rolled,
                // Damage is not a d20 and carries no crit range of its
                // own. Thresholds here would be a pair nothing judged.
                None,
                None,
                None,
                None,
                "damage",
            ));
        }
    }

    // WHAT THE DAMAGE DID, read fresh rather than taken from the client.
    // Whether a hit kills outright, and whether it costs a death save,
    // are rules with a body on the end of them - the dropdown's copy of
    // the goblin's hit points may be seconds stale.
    let mut vitals_update: Option<Value> = None;
    if let (Some(total), Some("actor"), Some(actor)) =
        (damage_total, target_row.as_deref(), target_id.as_deref())
    {
        if let Some(v) = encounter::load_actor_vitals(&session.access_token, actor)? {
            let was = death::condition(v.hp_current, v.successes, v.failures, v.dead);
            // Damage never earns a death save SUCCESS, so successes
            // ride along unchanged - only failures and death move.
            let successes = v.successes;
            let mut failures = v.failures;
            let mut dead = v.dead;

            // OVERFLOW FIRST, AND FOR EVERYONE. This used to sit
            // behind `was.is_conscious()`, so it ran on the blow that
            // dropped a creature and never again - which is how a
            // goblin reached -35 of 7 while still rolling saves. The
            // book checks it every time damage lands: at zero there is
            // nothing left to subtract, so the whole blow is overflow
            // and the raw damage is weighed against the maximum.
            //
            // `hp_current` is floored, which is what lets one
            // expression cover both cases - see death::overflow.
            let over = death::overflow(v.hp_current, total);
            if over >= 0 {
                if let Some(max) = v.hp_max {
                    if death::massive_damage_kills(over, max) {
                        dead = true;
                    }
                }
            }

            // Hitting someone already down is not free: a failure, and
            // two on a crit. This is the cost of letting a downed
            // creature stay in the target list. Skipped when the blow
            // just killed outright - a death save tally on something
            // already dead is bookkeeping nobody reads.
            if !dead && !was.is_conscious() {
                let crit = first.outcome == Some(dice::Outcome::Crit);
                failures = (failures + death::failures_from_being_hit(crit)).min(3);
            }

            if failures != v.failures || dead != v.dead {
                vitals_update = Some(vitals_payload(
                    &v.character_id,
                    successes,
                    failures,
                    dead,
                ));
            }
        }
    }

    // The hit points this cost, when it cost any. Damage that was not
    // aimed at an actor lands nowhere on purpose: a swing at a typed
    // number has nothing in the world to take it.
    let hp = damage_total.and_then(|total| {
        if target_row.as_deref() != Some("actor") {
            return None;
        }
        let actor = target_id.as_ref()?;
        // XOR, per 013. A character's hit points belong to the character
        // and follow them between encounters; an NPC instance's belong
        // to the instance, which is what lets two goblins off one
        // statblock bleed separately.
        let (character_id, actor_id) = match &target_character_id {
            Some(c) => (Some(c.clone()), None),
            None => (None, Some(actor.clone())),
        };
        Some(json!({
            "game_id": sheet.game_id,
            "character_id": character_id,
            "actor_id": actor_id,
            // SIGNED. Damage is negative; current HP is the maximum plus
            // the sum of these.
            "delta": -total,
        }))
    });

    let (target_actor_id, target_challenge_id) = match target_row.as_deref() {
        Some("actor") => (target_id.clone(), None),
        Some("challenge") => (None, target_id.clone()),
        _ => (None, None),
    };

    // One call. The action, every roll under it, and the hit points it
    // cost land together or not at all — see 012 and 014. A goblin that
    // took damage from a swing that does not exist is the failure this
    // prevents.
    supabase::rpc(
        &session.access_token,
        "write_action",
        &json!({
            "p_action": {
                "game_id": sheet.game_id,
                "character_id": sheet.character_id,
                "encounter_id": encounter_id,
                "actor_id": actor_id,
                "target_actor_id": target_actor_id,
                "target_challenge_id": target_challenge_id,
                "request": request,
                "label": resolved.label,
                "key": resolved.key,
            },
            "p_rolls": rolls,
            "p_hp": hp,
            "p_vitals": vitals_update,
        }),
    )
}

/// Where a death save tally is written.
///
/// ONE PLACE SINCE 022. This used to choose between a character row and
/// an actor row, because an NPC instance had no character to keep its
/// tally on. Every participant is a character now, so the choice is
/// gone - and two goblins off one statblock still die separately,
/// because they are two characters rather than two views of one.
fn vitals_payload(
    character_id: &Option<String>,
    successes: i64,
    failures: i64,
    dead: bool,
) -> Value {
    json!({
        "character_id": character_id,
        "death_successes": successes,
        "death_failures": failures,
        "dead": dead,
    })
}

/// One death saving throw, for whoever is dying.
///
/// No modifier applies, so this is a bare d20 and the rule reads the
/// FACE rather than a total - see death.rs. It is an action like any
/// other: every roll gets one, and this one is a creature spending its
/// turn on staying alive.
///
/// ON DEMAND RATHER THAN AUTOMATIC, because a dying creature saves on
/// its own turn and turn order does not exist yet.
/// `encounter_actors.initiative` has been waiting unread since 011 for
/// exactly this. The rule that decides the outcome is the same either
/// way; only what fires it changes.
#[tauri::command]
fn death_save(
    state: State<AppState>,
    game_id: String,
    actor_id: String,
    encounter_id: Option<String>,
) -> Result<Value, String> {
    let session = state
        .current()?
        .ok_or_else(|| "not signed in".to_string())?;

    let v = encounter::load_actor_vitals(&session.access_token, &actor_id)?
        .ok_or_else(|| "that actor is not in the encounter".to_string())?;

    // Asked, not decided here. This guard used to refuse conscious and
    // dead and let STABLE through, so a creature that had finished
    // dying could roll again and start over. "May this thing roll" is a
    // question about the game, so it lives in death.rs with tests.
    let was = death::condition(v.hp_current, v.successes, v.failures, v.dead);
    death::may_roll_death_save(was)?;

    let rolled = dice::roll_formula("1d20")?;
    let face = rolled.natural.unwrap_or(rolled.total);
    let outcome = death::save(face);

    let (successes, failures) = if outcome.clears_counters {
        (0, 0)
    } else {
        (
            (v.successes + outcome.successes).min(3),
            (v.failures + outcome.failures).min(3),
        )
    };

    // A natural 20 brings them back on one hit point, which is an
    // hp_event like any other rather than a special case.
    let hp = if outcome.hp_regain > 0 {
        Some(match &v.character_id {
            Some(c) => json!({
                "game_id": game_id, "character_id": c, "actor_id": null,
                "delta": outcome.hp_regain, "note": "death save: natural 20",
            }),
            None => json!({
                "game_id": game_id, "character_id": null, "actor_id": actor_id,
                "delta": outcome.hp_regain, "note": "death save: natural 20",
            }),
        })
    } else {
        None
    };

    let roll = json!({
        "game_id": game_id,
        "character_id": v.character_id,
        // WHOSE death save this was. For a character the 001 trigger
        // derives this from character_id and does it better than we
        // could; for an NPC there is no character row to derive from and
        // it falls through to the 'Someone' default, which leaves the
        // log unable to say which goblin was dying. The trigger only
        // fills a name that arrived null, blank or 'Someone', so handing
        // it the instance label here is not fighting it.
        "character_name": if v.character_id.is_none() { Some(v.label.clone()) } else { None },
        "owner_uid": session.user_id,
        "role": "check",
        "request": "death save",
        "label": "Death Save",
        "mode": "normal",
        "formula": "1d20",
        "detail": rolled.detail,
        "total": rolled.total,
        "natural_roll": rolled.natural,
        "status": "resolved",
    });

    supabase::rpc(
        &session.access_token,
        "write_action",
        &json!({
            "p_action": {
                "game_id": game_id,
                "character_id": v.character_id,
                "encounter_id": encounter_id,
                "actor_id": actor_id,
                "request": "death save",
                "label": "Death Save",
                "key": "death",
            },
            "p_rolls": [roll],
            "p_hp": hp,
            "p_vitals": vitals_payload(&v.character_id, successes, failures, false),
        }),
    )
}

/// One roll row, ready for `write_action`.
///
/// character_name and roller_name are left out on purpose — the
/// snapshot trigger fills them, so a client cannot forget or fake them.
#[allow(clippy::too_many_arguments)]
fn roll_row(
    sheet: &Sheet,
    session: &Session,
    request: &str,
    label: &str,
    mode: &str,
    formula: &str,
    rolled: &RollResult,
    thresholds: Option<dice::Thresholds>,
    narrative: Option<String>,
    target: Option<&Target>,
    verdict: Option<&resolution::Resolution>,
    role: &str,
) -> Value {
    let mut row = json!({
        "game_id": sheet.game_id,
        "character_id": sheet.character_id,
        // WHOSE ACTION THIS WAS, when nothing can derive it.
        //
        // The 001 trigger reads the name off character_id and does it
        // better than we could. A monster has no character row, so it
        // falls through to the 'Someone' default and the log stops being
        // able to say which goblin swung. The sheet's name IS the
        // actor's label in that case — the same fix 421d08c made for
        // death saves, now covering every roll a monster makes.
        "character_name": match &sheet.character_id {
            Some(_) => None,
            None => Some(sheet.name.clone()),
        },
        "owner_uid": session.user_id,
        "request": request,
        "label": label,
        "mode": mode,
        "formula": formula,
        "detail": rolled.detail,
        "total": rolled.total,
        "natural_roll": rolled.natural,
        "face_outcome": rolled.outcome,
        "narrative": narrative,
        "status": "resolved",
        "role": role,
    });

    // The thresholds go on the row only when a face was actually judged,
    // matching the column comments: null means no d20, not 20 and 1.
    if let (Some(t), Some(_)) = (thresholds, rolled.natural) {
        row["crit_min"] = json!(t.crit_min);
        row["fumble_max"] = json!(t.fumble_max);
    }

    if let (Some(t), Some(v)) = (target, verdict) {
        row["target_value"] = json!(t.value);
        row["target_kind"] = json!(t.kind.as_str());
        row["target_label"] = json!(t.label);
        row["success"] = json!(v.success);
        row["reason"] = json!(v.reason.as_str());
        row["margin"] = json!(v.margin);
    }

    row
}

/// Both target inputs or neither.
///
/// A value with no kind cannot be resolved - the auto-hit rule needs to
/// know whether it is an AC or a DC - and silently treating it as one or
/// the other would decide a roll on a guess. Half a target is refused
/// rather than defaulted.
fn parse_target(
    value: Option<i64>,
    kind: Option<String>,
    label: Option<String>,
) -> Result<Option<Target>, String> {
    match (value, kind.as_deref().map(str::trim).filter(|k| !k.is_empty())) {
        (None, None) => Ok(None),
        (Some(v), Some(k)) => {
            let kind = TargetKind::parse(k)
                .ok_or_else(|| format!("target kind must be ac or dc, got \"{}\"", k))?;
            Ok(Some(Target {
                value: v,
                kind,
                label: label
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty()),
            }))
        }
        (Some(_), None) => Err("a target value needs a kind: ac or dc".to_string()),
        (None, Some(_)) => Err("a target kind needs a value to beat".to_string()),
    }
}

/* ============================ ENCOUNTERS ============================ */

/// The encounters in a game, newest first. `active` is the one in front
/// of the table; at most one per game, enforced by a partial unique
/// index rather than by hope.
#[tauri::command]
fn list_encounters(state: State<AppState>, game_id: String) -> Result<Value, String> {
    let token = state.token()?;
    supabase::rest_get(
        &token,
        "encounters",
        &[
            ("select", "id,name,status,created_at"),
            ("game_id", &format!("eq.{}", game_id)),
            ("order", "created_at.desc"),
        ],
    )
}

/// Everything in an encounter a roll can be aimed at: actors with their
/// resolved AC, challenges with their DC, in one list.
///
/// The AC is worked out per actor rather than read off a column - see
/// encounter.rs. A character's is computed from what they are wearing by
/// the same function their own sheet uses, so the DM's target list and
/// the player's sheet cannot disagree about what it takes to hit them.
#[tauri::command]
fn list_targets(
    state: State<AppState>,
    encounter_id: String,
) -> Result<Vec<encounter::Target>, String> {
    let token = state.token()?;
    encounter::load_targets(&token, &encounter_id)
}

/* ============================ ENTRY ============================ */

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .manage(AppState::default())
        .invoke_handler(tauri::generate_handler![
            sign_up,
            sign_in,
            sign_out,
            // A path registers exactly like a bare name, and the command
            // is still "me" on the wire. See commands/mod.rs.
            commands::session::me,
            // Fast login. Convenience, not security - see pin.rs.
            commands::session::pin_status,
            commands::session::set_pin,
            commands::session::unlock,
            commands::session::forget_pin,
            list_games,
            create_game,
            join_game,
            list_members,
            list_characters,
            create_character,
            list_rolls,
            list_encounters,
            list_targets,
            // The DM side. Eleven commands, none of them in this file —
            // see commands/mod.rs for why that is the point.
            commands::inventory::list_catalogue,
            commands::inventory::give_item,
            commands::inventory::drop_object,
            commands::inventory::take_object,
            commands::inventory::rename_object,
            commands::inventory::destroy_object,
            commands::dm::list_npcs,
            commands::dm::create_npc,
            commands::dm::create_encounter,
            commands::dm::set_encounter_status,
            commands::dm::enrol_actor,
            commands::dm::remove_actor,
            commands::dm::set_actor_active,
            commands::dm::add_challenge,
            commands::dm::set_challenge_active,
            commands::dm::list_roster,
            commands::dm::list_challenges,
            commands::dm::list_skill_keys,
            // A monster acts. Both go through the same `swing` a
            // character's attack does — see 019.
            commands::dm::list_npc_attacks,
            commands::dm::npc_attack,
            commands::dm::view_actor,
            commands::dm::rename_actor,
            death_save,
            get_sheet,
            set_level,
            set_ability,
            set_skill_prof,
            list_inventory,
            set_item_equipped,
            check_item_keys,
            preview_request,
            roll_named,
            roll_dice,
            create_roll,
            patch_roll_narrative,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
