-- 103. THE CLERIC LIST: 3rd, 4th AND 5th.
--
-- The middle third. Same contract as 102: the text is ours, `dice` is
-- the base with no modifier folded in, and an existing key is updated
-- rather than duplicated.

insert into spells
  (key, name, roll_name, level, cast_type, category, school, save_ability,
   dice, concentration, ritual, range, duration, casting_time,
   components, material, classes, description)
values
-- ================================ 3rd ================================
('sp_animatedead','Animate Dead','Animate Dead',3,'Utility','3rd Circle','necromancy',null,
 null,false,false,'10 feet','Instantaneous','1 minute',array['v','s','m'],'a drop of blood, a piece of flesh and a pinch of bone dust',array['cleric','wizard'],
 'A corpse or pile of bones becomes a skeleton or zombie under your command. The command lasts 24 hours and must be renewed by recasting, or it turns on you.'),
('sp_beaconofhope','Beacon of Hope','Beacon of Hope',3,'Utility','3rd Circle','abjuration',null,
 null,true,false,'30 feet','Up to 1 minute','1 action',array['v','s'],null,array['cleric'],
 'Chosen creatures gain advantage on Wisdom saves and death saves, and regain the maximum from any healing.'),
('sp_bestowcurse','Bestow Curse','Bestow Curse',3,'Save','3rd Circle','necromancy','wis',
 '1d8',true,false,'Touch','Up to 1 minute','1 action',array['v','s'],null,array['cleric','bard','wizard'],
 'A creature that fails a Wisdom save takes one of four curses: disadvantage on an ability of your choice, disadvantage against you, a wasted turn on a failed save, or 1d8 extra necrotic from your attacks.'),
('sp_clairvoyance','Clairvoyance','Clairvoyance',3,'Utility','3rd Circle','divination',null,
 null,true,false,'1 mile','Up to 10 minutes','10 minutes',array['v','s','m'],'a focus worth 100 gp - a horn for hearing, a glass eye for seeing',array['cleric','bard','sorcerer','wizard'],
 'An invisible sensor appears at a place you know or can see, and you can see or hear from it.'),
('sp_createfoodandwater','Create Food and Water','Create Food and Water',3,'Utility','3rd Circle','conjuration',null,
 null,false,false,'30 feet','Instantaneous','1 action',array['v','s'],null,array['cleric','paladin'],
 'Food enough for fifteen people for a day, and thirty gallons of water. The food is bland and spoils in 24 hours.'),
('sp_daylight','Daylight','Daylight',3,'Utility','3rd Circle','evocation',null,
 null,false,false,'60 feet','1 hour','1 action',array['v','s'],null,array['cleric','druid','paladin','ranger','sorcerer'],
 'A 60-foot sphere of bright light with 60 more of dim. It is not sunlight, whatever it looks like - creatures that burn in the sun do not burn in this.'),
('sp_dispelmagic','Dispel Magic','Dispel Magic',3,'Utility','3rd Circle','abjuration',null,
 null,false,false,'120 feet','Instantaneous','1 action',array['v','s'],null,array['cleric','bard','druid','paladin','sorcerer','warlock','wizard'],
 'Ends a spell of 3rd level or lower on a creature, object or effect. Anything higher needs an ability check against the caster, or a bigger slot.'),
('sp_feigndeath','Feign Death','Feign Death',3,'Utility','3rd Circle','necromancy',null,
 null,false,true,'Touch','1 hour','1 action',array['v','s','m'],'a pinch of graveyard dirt',array['cleric','bard','druid','wizard'],
 'A willing creature appears dead: blinded, incapacitated, with resistance to everything but psychic, and no disease or poison progresses.'),
('sp_glyphofwarding','Glyph of Warding','Glyph of Warding',3,'Utility','3rd Circle','abjuration',null,
 '5d8',false,false,'Touch','Until dispelled or triggered','1 hour',array['v','s','m'],'incense and powdered diamond worth 200 gp, consumed',array['cleric','bard','wizard'],
 'A hidden glyph that goes off on a trigger you set - an explosion of 5d8, or a stored spell of 3rd level or lower.'),
('sp_magiccircle','Magic Circle','Magic Circle',3,'Utility','3rd Circle','abjuration','cha',
 null,false,false,'10 feet','1 hour','1 minute',array['v','s','m'],'holy water or powdered silver and iron worth 100 gp, consumed',array['cleric','paladin','warlock','wizard'],
 'A 10-foot cylinder that a chosen creature type cannot willingly enter, and cannot charm, frighten or possess across. Reversed, it keeps one in.'),
('sp_masshealingword','Mass Healing Word','Mass Healing Word',3,'Heal','3rd Circle','evocation',null,
 '1d4',false,false,'60 feet','Instantaneous','1 bonus action',array['v'],null,array['cleric'],
 'Up to six creatures each regain 1d4 plus your spellcasting modifier. A bonus action, which is what it is for.'),
('sp_meldintostone','Meld into Stone','Meld into Stone',3,'Utility','3rd Circle','transmutation',null,
 null,false,true,'Touch','8 hours','1 action',array['v','s'],null,array['cleric','druid'],
 'You step into a stone object or surface big enough to hold you, and can see and hear nothing outside it.'),
('sp_protectionfromenergy','Protection from Energy','Protection from Energy',3,'Utility','3rd Circle','abjuration',null,
 null,true,false,'Touch','Up to 1 hour','1 action',array['v','s'],null,array['cleric','druid','ranger','sorcerer','wizard'],
 'A creature gains resistance to one of acid, cold, fire, lightning or thunder.'),
('sp_removecurse','Remove Curse','Remove Curse',3,'Utility','3rd Circle','abjuration',null,
 null,false,false,'Touch','Instantaneous','1 action',array['v','s'],null,array['cleric','paladin','warlock','wizard'],
 'Ends every curse on a creature, and breaks the attunement to a cursed item - though the curse on the item itself remains.'),
('sp_revivify','Revivify','Revivify',3,'Heal','3rd Circle','necromancy',null,
 null,false,false,'Touch','Instantaneous','1 action',array['v','s','m'],'diamonds worth 300 gp, consumed',array['cleric','paladin'],
 'A creature dead no more than a minute returns with 1 hit point. It restores no missing parts and will not raise anything that died of old age.'),
('sp_sending','Sending','Sending',3,'Utility','3rd Circle','evocation',null,
 null,false,false,'Unlimited','1 round','1 action',array['v','s','m'],'a short copper wire',array['cleric','bard','wizard'],
 'Twenty-five words to a creature you know, anywhere, and it may answer in twenty-five. Across planes there is a chance it simply does not arrive.'),
('sp_speakwithdead','Speak with Dead','Speak with Dead',3,'Utility','3rd Circle','necromancy',null,
 null,false,false,'10 feet','10 minutes','1 action',array['v','s','m'],'burning incense',array['cleric','bard'],
 'A corpse with a mouth answers five questions. It knows only what it knew in life, it may be evasive, and it will not answer twice within ten days.'),
('sp_spiritguardians','Spirit Guardians','Spirit Guardians',3,'Save','3rd Circle','conjuration','wis',
 '3d8',true,false,'Self (15-foot radius)','Up to 10 minutes','1 action',array['v','s','m'],'a holy symbol',array['cleric'],
 'Spirits fill a 15-foot radius around you. Enemies there move at half speed and take 3d8 radiant or necrotic, halved on a Wisdom save.'),
('sp_tongues','Tongues','Tongues',3,'Utility','3rd Circle','divination',null,
 null,false,false,'Touch','1 hour','1 action',array['v','m'],'a small clay model of a ziggurat',array['cleric','bard','sorcerer','warlock','wizard'],
 'The target understands any spoken language, and anything with a language understands what it says.'),
('sp_waterwalk','Water Walk','Water Walk',3,'Utility','3rd Circle','transmutation',null,
 null,false,true,'30 feet','1 hour','1 action',array['v','s','m'],'a piece of cork',array['cleric','druid','ranger','sorcerer'],
 'Up to ten creatures can walk on any liquid surface as if it were solid ground.'),

-- ================================ 4th ================================
('sp_banishment','Banishment','Banishment',4,'Save','4th Circle','abjuration','cha',
 null,true,false,'60 feet','Up to 1 minute','1 action',array['v','s','m'],'an item distasteful to the target',array['cleric','paladin','sorcerer','warlock','wizard'],
 'A creature that fails a Charisma save is sent to a harmless demiplane. If it is native elsewhere and the spell lasts the full minute, it stays there.'),
('sp_controlwater','Control Water','Control Water',4,'Utility','4th Circle','transmutation',null,
 null,true,false,'300 feet','Up to 10 minutes','1 action',array['v','s','m'],'a drop of water and a pinch of dust',array['cleric','druid','wizard'],
 'Water in a large area rises as a flood, parts to the bottom, redirects, or turns into a whirlpool.'),
('sp_deathward','Death Ward','Death Ward',4,'Utility','4th Circle','abjuration',null,
 null,false,false,'Touch','8 hours','1 action',array['v','s'],null,array['cleric','paladin'],
 'The first time the creature would drop to 0 hit points it drops to 1 instead, and an effect that would kill it outright simply fails. Then the spell ends.'),
('sp_divination','Divination','Divination',4,'Utility','4th Circle','divination',null,
 null,false,true,'Self','Instantaneous','1 action',array['v','s','m'],'incense and a sacrifice worth 25 gp, consumed',array['cleric'],
 'A truthful reply about one goal, event or activity within seven days - a short phrase, a rhyme, an omen. Casting it more than once a day risks a false answer.'),
('sp_freedomofmovement','Freedom of Movement','Freedom of Movement',4,'Utility','4th Circle','abjuration',null,
 null,false,false,'Touch','1 hour','1 action',array['v','s','m'],'a leather strap bound round the arm',array['cleric','bard','druid','ranger'],
 'Difficult terrain costs the creature nothing, and nothing can reduce its speed, paralyse or restrain it. It can also spend 5 feet to escape a grapple.'),
('sp_guardianoffaith','Guardian of Faith','Guardian of Faith',4,'Save','4th Circle','conjuration','dex',
 null,false,false,'30 feet','8 hours','1 action',array['v'],null,array['cleric'],
 'A Large spectral guardian stands where you put it. An enemy that comes within 10 feet takes 20 radiant, halved on a Dexterity save. It fades after 60 damage dealt.'),
('sp_locatecreature','Locate Creature','Locate Creature',4,'Utility','4th Circle','divination',null,
 null,true,false,'Self (1,000 feet)','Up to 1 hour','1 action',array['v','s','m'],'a tuft of fur from a bloodhound',array['cleric','bard','druid','paladin','ranger','wizard'],
 'You sense the direction of a creature you know or a kind you have seen, within 1,000 feet. Running water blocks it.'),
('sp_stoneshape','Stone Shape','Stone Shape',4,'Utility','4th Circle','transmutation',null,
 null,false,false,'Touch','Instantaneous','1 action',array['v','s','m'],'soft clay shaped into the form you want',array['cleric','druid','wizard'],
 'A stone object of up to 5 feet takes any shape you like - a door, a weapon, a passage - with no fine detail.'),

-- ================================ 5th ================================
('sp_commune','Commune','Commune',5,'Utility','5th Circle','divination',null,
 null,false,true,'Self','1 minute','1 minute',array['v','s','m'],'incense and a vial of holy water',array['cleric'],
 'Three yes-or-no questions to your deity, answered truthfully. Casting it more than once a day risks a random answer.'),
('sp_contagion','Contagion','Contagion',5,'Save','5th Circle','necromancy','con',
 null,false,false,'Touch','7 days','1 action',array['v','s'],null,array['cleric','druid'],
 'A melee spell attack inflicts a disease of your choice. Three failed Constitution saves and it takes hold for seven days; three successes and it ends.'),
('sp_dispelevilandgood','Dispel Evil and Good','Dispel Evil and Good',5,'Utility','5th Circle','abjuration','cha',
 null,true,false,'Self','Up to 1 minute','1 action',array['v','s','m'],'holy water or powdered silver and iron',array['cleric','paladin'],
 'Celestials, elementals, fey, fiends and undead have disadvantage to hit you, and you may spend an action to break a possession, dismiss one, or end a charm.'),
('sp_flamestrike','Flame Strike','Flame Strike',5,'Save','5th Circle','evocation','dex',
 '4d6',false,false,'60 feet','Instantaneous','1 action',array['v','s','m'],'a pinch of sulphur',array['cleric'],
 'A column of divine fire in a 10-foot radius, 40 feet high: 4d6 fire and 4d6 radiant, halved on a Dexterity save.'),
('sp_geas','Geas','Geas',5,'Save','5th Circle','enchantment','wis',
 '5d10',false,false,'60 feet','30 days','1 minute',array['v'],null,array['cleric','bard','druid','paladin','wizard'],
 'A creature that fails a Wisdom save must carry out an order for thirty days, taking 5d10 psychic each day it acts against it.'),
('sp_greaterrestoration','Greater Restoration','Greater Restoration',5,'Utility','5th Circle','abjuration',null,
 null,false,false,'Touch','Instantaneous','1 action',array['v','s','m'],'diamond dust worth 100 gp, consumed',array['cleric','bard','druid'],
 'Ends one of: a charm, a petrification, a curse, a reduced ability score, or a reduced hit point maximum.'),
('sp_hallow','Hallow','Hallow',5,'Utility','5th Circle','evocation','cha',
 null,false,false,'Touch','Until dispelled','24 hours',array['v','s','m'],'herbs, oils and incense worth 1,000 gp, consumed',array['cleric'],
 'An area up to 60 feet becomes holy ground: a chosen creature type cannot enter or possess across it, and you bind a second effect to it as well.'),
('sp_insectplague','Insect Plague','Insect Plague',5,'Save','5th Circle','conjuration','con',
 '4d10',true,false,'300 feet','Up to 10 minutes','1 action',array['v','s','m'],'a few grains of sugar, some kernels of grain and a smear of fat',array['cleric','druid','sorcerer'],
 'A 20-foot sphere of biting insects: 4d10 piercing on a failed Constitution save, half on a success, and the whole area is difficult terrain and lightly obscured.'),
('sp_legendlore','Legend Lore','Legend Lore',5,'Utility','5th Circle','divination',null,
 null,false,false,'Self','Instantaneous','10 minutes',array['v','s','m'],'incense worth 250 gp and four ivory strips worth 50 gp each, consumed',array['cleric','bard','wizard'],
 'What you know of a famous person, place or thing comes back as lore - clear if it is legendary, cryptic if it is merely notable, nothing if it is neither.'),
('sp_masscurewounds','Mass Cure Wounds','Mass Cure Wounds',5,'Heal','5th Circle','evocation',null,
 '3d8',false,false,'60 feet','Instantaneous','1 action',array['v','s'],null,array['cleric','bard','druid'],
 'Up to six creatures in a 30-foot sphere each regain 3d8 plus your spellcasting modifier.'),
('sp_planarbinding','Planar Binding','Planar Binding',5,'Save','5th Circle','abjuration','cha',
 null,false,false,'60 feet','24 hours','1 hour',array['v','s','m'],'a jewel worth 1,000 gp, consumed',array['cleric','bard','druid','wizard'],
 'A celestial, elemental, fey or fiend already bound in place must pass a Charisma save or serve you for 24 hours. A bigger slot buys longer, up to a year.'),
('sp_raisedead','Raise Dead','Raise Dead',5,'Heal','5th Circle','necromancy',null,
 null,false,false,'Touch','Instantaneous','1 hour',array['v','s','m'],'a diamond worth 500 gp, consumed',array['cleric','bard','paladin'],
 'A creature dead up to ten days returns with 1 hit point. It takes a -4 penalty to every d20 roll, wearing off over several long rests, and missing parts stay missing.'),
('sp_scrying','Scrying','Scrying',5,'Save','5th Circle','divination','wis',
 null,true,false,'Self','Up to 10 minutes','10 minutes',array['v','s','m'],'a focus worth 1,000 gp - a crystal ball, a mirror, a font of holy water',array['cleric','bard','druid','warlock','wizard'],
 'You see and hear a creature anywhere on the same plane. It saves against it, and the better you know it or the more of it you hold, the harder that save becomes.')

on conflict (key) where game_id is null do update set
  name = excluded.name, roll_name = excluded.roll_name, level = excluded.level,
  cast_type = excluded.cast_type, category = excluded.category,
  school = excluded.school, save_ability = excluded.save_ability,
  dice = excluded.dice, concentration = excluded.concentration,
  ritual = excluded.ritual, range = excluded.range, duration = excluded.duration,
  casting_time = excluded.casting_time, components = excluded.components,
  material = excluded.material, classes = excluded.classes,
  description = excluded.description,
  spell_atk = null, dc = null;