-- 104. THE CLERIC LIST: 6th THROUGH 9th.
--
-- The last third, and the list is complete at 106 spells. Same
-- contract as 102 and 103.

insert into spells
  (key, name, roll_name, level, cast_type, category, school, save_ability,
   dice, concentration, ritual, range, duration, casting_time,
   components, material, classes, description)
values
-- ================================ 6th ================================
('sp_bladebarrier','Blade Barrier','Blade Barrier',6,'Save','6th Circle','evocation','dex',
 '6d10',true,false,'90 feet','Up to 10 minutes','1 action',array['v','s'],null,array['cleric'],
 'A wall of whirling blades, straight or ringed. Passing through costs 6d10 slashing, halved on a Dexterity save, and the whole wall is difficult terrain.'),
('sp_createundead','Create Undead','Create Undead',6,'Utility','6th Circle','necromancy',null,
 null,false,false,'10 feet','Instantaneous','1 minute',array['v','s','m'],'a black onyx stone worth 150 gp for each corpse, and an alchemical vial',array['cleric','warlock','wizard'],
 'Up to three corpses become ghouls under your command for 24 hours, renewed by recasting. Cast at night only. A bigger slot makes stronger undead.'),
('sp_findthepath','Find the Path','Find the Path',6,'Utility','6th Circle','divination',null,
 null,true,false,'Self','Up to 1 day','1 minute',array['v','s','m'],'divinatory tools worth 100 gp and an object from the destination',array['cleric','bard','druid'],
 'You know the shortest route to a place you are familiar with on the same plane, and which way it lies at all times.'),
('sp_forbiddance','Forbiddance','Forbiddance',6,'Utility','6th Circle','abjuration',null,
 '5d10',false,true,'Touch','1 day','10 minutes',array['v','s','m'],'holy water, incense and powdered ruby worth 1,000 gp',array['cleric'],
 'An area is warded against teleport and planar travel, and a chosen creature type takes 5d10 radiant or necrotic entering it. Cast daily for 30 days and it becomes permanent.'),
('sp_harm','Harm','Harm',6,'Save','6th Circle','necromancy','con',
 '14d6',false,false,'60 feet','Instantaneous','1 action',array['v','s'],null,array['cleric'],
 '14d6 necrotic on a failed Constitution save, half on a success - and on a failure the maximum drops by the same amount for an hour. It cannot reduce below 1.'),
('sp_heal','Heal','Heal',6,'Heal','6th Circle','evocation',null,
 null,false,false,'60 feet','Instantaneous','1 action',array['v','s'],null,array['cleric','druid'],
 '70 hit points restored, and blindness, deafness and every disease ended. Nothing for a construct or the undead. Ten more per slot level above 6th.'),
('sp_heroesfeast','Heroes'' Feast','Heroes'' Feast',6,'Heal','6th Circle','conjuration',null,
 '2d10',false,false,'30 feet','Instantaneous','10 minutes',array['v','s','m'],'a gem-encrusted bowl worth 1,000 gp, consumed',array['cleric','druid'],
 'A feast for twelve, taking an hour to eat. For 24 hours each diner is cured of disease and poison, immune to both and to being frightened, has advantage on Wisdom saves, and gains 2d10 maximum and current hit points.'),
('sp_planarally','Planar Ally','Planar Ally',6,'Utility','6th Circle','conjuration',null,
 null,false,false,'60 feet','Instantaneous','10 minutes',array['v','s'],null,array['cleric'],
 'You call on your deity and a celestial, elemental or fiend of their choosing appears. It is not compelled to serve - it will name a price, and the DM decides what.'),
('sp_trueseeing','True Seeing','True Seeing',6,'Utility','6th Circle','divination',null,
 null,false,false,'Touch','1 hour','1 action',array['v','s','m'],'an ointment for the eyes worth 25 gp, consumed',array['cleric','bard','sorcerer','warlock','wizard'],
 'For an hour the creature has truesight to 120 feet: it sees the invisible, through illusions and shapechanges, into the Ethereal, and in the dark.'),
('sp_wordofrecall','Word of Recall','Word of Recall',6,'Utility','6th Circle','conjuration',null,
 null,false,false,'5 feet','Instantaneous','1 action',array['v'],null,array['cleric'],
 'You and up to five willing creatures teleport instantly to a sanctuary you designated beforehand.'),

-- ================================ 7th ================================
('sp_conjurecelestial','Conjure Celestial','Conjure Celestial',7,'Utility','7th Circle','conjuration',null,
 null,true,false,'90 feet','Up to 1 hour','1 minute',array['v','s'],null,array['cleric'],
 'A celestial of challenge 4 or lower appears and acts on its own initiative, friendly but not commanded. A 9th-level slot calls one of challenge 5.'),
('sp_divineword','Divine Word','Divine Word',7,'Save','7th Circle','evocation','cha',
 null,false,false,'30 feet','Instantaneous','1 bonus action',array['v'],null,array['cleric'],
 'A word of creation. Creatures that fail a Charisma save are deafened, blinded, stunned or killed outright depending on how many hit points they have left.'),
('sp_etherealness','Etherealness','Etherealness',7,'Utility','7th Circle','transmutation',null,
 null,false,false,'Self','Up to 8 hours','1 action',array['v','s'],null,array['cleric','bard','sorcerer','warlock','wizard'],
 'You step onto the Ethereal Plane, able to move in any direction and see the world you left as grey and 60 feet distant.'),
('sp_firestorm','Fire Storm','Fire Storm',7,'Save','7th Circle','evocation','dex',
 '7d10',false,false,'150 feet','Instantaneous','1 action',array['v','s'],null,array['cleric','druid','sorcerer'],
 'Ten 10-foot cubes of flame you place as you like: 7d10 fire, halved on a Dexterity save. It leaves plants and objects you choose untouched.'),
('sp_planeshift','Plane Shift','Plane Shift',7,'Save','7th Circle','conjuration','cha',
 null,false,false,'Touch','Instantaneous','1 action',array['v','s','m'],'a forked metal rod attuned to the destination plane, worth 250 gp',array['cleric','druid','sorcerer','warlock','wizard'],
 'You and up to eight willing creatures travel to another plane, or one unwilling creature that fails a Charisma save is banished there.'),
('sp_regenerate','Regenerate','Regenerate',7,'Heal','7th Circle','transmutation',null,
 '4d8',false,false,'Touch','1 hour','1 minute',array['v','s','m'],'a prayer wheel and holy water',array['cleric','bard','druid'],
 '4d8 plus 15 restored at once, then 1 per turn for an hour - and a severed limb regrows in two minutes.'),
('sp_resurrection','Resurrection','Resurrection',7,'Heal','7th Circle','necromancy',null,
 null,false,false,'Touch','Instantaneous','1 hour',array['v','s','m'],'a diamond worth 1,000 gp, consumed',array['cleric','bard'],
 'A creature dead up to a century returns at full hit points, whole again, with a -4 penalty to d20 rolls that wears off over several long rests.'),
('sp_symbol','Symbol','Symbol',7,'Save','7th Circle','abjuration',null,
 null,false,false,'Touch','Until dispelled or triggered','1 minute',array['v','s','m'],'mercury, phosphorus and powdered diamond and opal worth 1,000 gp, consumed',array['cleric','bard','wizard'],
 'A glyph that goes off on your chosen trigger with one of eight effects - death, discord, fear, hopelessness, insanity, pain, sleep or stunning.'),

-- ================================ 8th ================================
('sp_antimagicfield','Antimagic Field','Antimagic Field',8,'Utility','8th Circle','abjuration',null,
 null,true,false,'Self (10-foot radius)','Up to 1 hour','1 action',array['v','s','m'],'a pinch of powdered iron filings',array['cleric','wizard'],
 'A 10-foot sphere where magic simply does not work: no spells, no magic items, no summoned creatures, and nothing can be cast into it or out.'),
('sp_controlweather','Control Weather','Control Weather',8,'Utility','8th Circle','transmutation',null,
 null,true,false,'Self (5-mile radius)','Up to 8 hours','10 minutes',array['v','s','m'],'burning incense and bits of earth and wood mixed in water',array['cleric','druid','wizard'],
 'You change precipitation, temperature and wind within five miles, one stage at a time, and it takes 1d4 x 10 minutes to take hold.'),
('sp_earthquake','Earthquake','Earthquake',8,'Save','8th Circle','evocation','dex',
 null,true,false,'500 feet','Up to 1 minute','1 action',array['v','s','m'],'a pinch of dirt, a piece of rock and a lump of clay',array['cleric','druid','sorcerer'],
 'The ground shakes in a 100-foot radius: creatures fall prone, structures take damage and collapse, and fissures open and swallow what stands over them.'),
('sp_holyaura','Holy Aura','Holy Aura',8,'Save','8th Circle','abjuration','con',
 null,true,false,'Self','Up to 1 hour','1 action',array['v','s','m'],'a tiny reliquary worth 1,000 gp holding a holy relic',array['cleric'],
 'Chosen creatures gain advantage on all saves, attacks against them have disadvantage, and a fiend or undead that hits one must save or be blinded.'),

-- ================================ 9th ================================
('sp_astralprojection','Astral Projection','Astral Projection',9,'Utility','9th Circle','necromancy',null,
 null,false,false,'10 feet','Special','1 hour',array['v','s','m'],'a jacinth worth 1,000 gp and a silver bar worth 100 gp per creature, consumed',array['cleric','warlock','wizard'],
 'You and up to eight others project into the Astral Plane, bodies left behind in suspended animation, joined by a silver cord that only a few things can cut.'),
('sp_gate','Gate','Gate',9,'Utility','9th Circle','conjuration',null,
 null,true,false,'60 feet','Up to 1 minute','1 action',array['v','s','m'],'a diamond worth 5,000 gp',array['cleric','sorcerer','warlock','wizard'],
 'A portal to another plane, up to 20 feet across. Speaking a creature''s name draws it through, if nothing shields it.'),
('sp_massheal','Mass Heal','Mass Heal',9,'Heal','9th Circle','evocation',null,
 null,false,false,'60 feet','Instantaneous','1 action',array['v','s'],null,array['cleric'],
 'Up to 700 hit points divided as you choose among creatures you can see, and every one of them is cured of disease, blindness and deafness.'),
('sp_trueresurrection','True Resurrection','True Resurrection',9,'Heal','9th Circle','necromancy',null,
 null,false,false,'Touch','Instantaneous','1 hour',array['v','s','m'],'holy water and diamonds worth 25,000 gp, consumed',array['cleric','druid'],
 'A creature dead up to 200 years returns at full hit points, whole, cured of everything, with no penalty at all - and it works even with no body left, if you speak the name.')

on conflict (key) where game_id is null do update set
  name = excluded.name, roll_name = excluded.roll_name, level = excluded.level,
  cast_type = excluded.cast_type, category = excluded.category,
  school = excluded.school, save_ability = excluded.save_ability,
  dice = excluded.dice, concentration = excluded.concentration,
  ritual = excluded.ritual, range = excluded.range, duration = excluded.duration,
  casting_time = excluded.casting_time, components = excluded.components,
  material = excluded.material, classes = excluded.classes,
  description = excluded.description,
  spell_atk = null, dc = null;