-- 161. THE WIZARD LIST: CANTRIPS AND FIRST CIRCLE.
--
-- 150 built the wizard as a CASTER and 151 gave the Mage and Lich the
-- handful of spells that happened to exist. There was no wizard list:
-- 108 spells, 106 cleric-legal, and exactly ONE wizard-and-not-cleric.
-- The SRD wizard list is 172; we hold 37. This is the first 34 of the
-- 135 missing, and 162-164 carry the rest.
--
-- THE TEXT IS OURS - 102's rule, held to for 106 cleric spells and
-- broken exactly twice, both in 105. Every description below says what
-- the spell DOES in one sentence. The mechanical values are the rules
-- themselves and were read off the published SRD.
--
-- DICE THAT ARE NOT DAMAGE DO NOT GO IN `dice`, which is 158's lesson
-- and bigger here: Sleep's 5d8 and Color Spray's 6d10 are pools of hit
-- points, False Life's 1d4+4 is temporary hit points. Those carry NULL
-- dice and say the number in special_text. Magic Missile keeps its dice
-- and is Utility rather than Attack - it has no attack roll to make.
--
-- Full reasoning, including what a wizard still cannot do with any of
-- this (nothing writes `book`, so a player wizard has an empty book and
-- no way to fill it), in
-- supabase/migrations/161_the_wizard_list_cantrips_and_first.sql.

insert into spells
  (key, name, roll_name, level, cast_type, category, school, save_ability, dice,
   concentration, ritual, range, duration, casting_time, components, material,
   classes, special_text, description)
values
('sp_acidsplash','Acid Splash','Acid Splash',0,'Save','Cantrips','conjuration','dex','1d6',
 false,false,'60 feet','Instant','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'Two targets only if they are within 5 feet of each other. 2d6 at 5th level, 3d6 at 11th, 4d6 at 17th.',
 'A bubble of acid thrown at one creature, or at two standing close enough to share it. A failed Dexterity save takes 1d6 acid; a successful one takes nothing.'),
('sp_chilltouch','Chill Touch','Chill Touch',0,'Attack','Cantrips','necromancy',null,'1d8',
 false,false,'120 feet','1 round','1 action',array['v','s'],null,
 array['sorcerer','warlock','wizard'],
 'The undead also have disadvantage on attacks against you until the end of your next turn. 2d8 at 5th level, 3d8 at 11th, 4d8 at 17th.',
 'A spectral hand grips the target at range: a spell attack for 1d8 necrotic, and it cannot regain hit points until the end of your next turn.'),
('sp_dancinglights','Dancing Lights','Dancing Lights',0,'Utility','Cantrips','evocation',null,null,
 true,false,'120 feet','Up to 1 minute','1 action',array['v','s','m'],'a bit of phosphorus',
 array['bard','sorcerer','wizard'],
 'Move them up to 60 feet as a bonus action; they must stay within 20 feet of each other.',
 'Four floating lights, each as bright as a torch, or the four combined into one vaguely humanoid shape.'),
('sp_firebolt','Fire Bolt','Fire Bolt',0,'Attack','Cantrips','evocation',null,'1d10',
 false,false,'120 feet','Instant','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'Unattended flammable objects catch fire. 2d10 at 5th level, 3d10 at 11th, 4d10 at 17th.',
 'A mote of fire hurled at one target: a spell attack for 1d10 fire damage.'),
('sp_magehand','Mage Hand','Mage Hand',0,'Utility','Cantrips','conjuration',null,null,
 false,false,'30 feet','1 minute','1 action',array['v','s'],null,
 array['bard','sorcerer','warlock','wizard'],
 'It cannot attack, activate magic items or carry more than 10 pounds.',
 'A spectral hand that fetches, opens, pours and carries at a distance, directed with an action.'),
('sp_message','Message','Message',0,'Utility','Cantrips','transmutation',null,null,
 false,false,'120 feet','1 round','1 action',array['v','s','m'],'a short piece of copper wire',
 array['bard','sorcerer','wizard'],
 'Stone, metal, wood and water block it; a thin sheet of lead stops it outright.',
 'A whisper that only one creature hears, and a whisper back that only you do.'),
('sp_minorillusion','Minor Illusion','Minor Illusion',0,'Utility','Cantrips','illusion',null,null,
 false,false,'30 feet','1 minute','1 action',array['s','m'],'a bit of fleece',
 array['bard','sorcerer','warlock','wizard'],
 'A creature that studies it may make an Investigation check against your save DC to see through it.',
 'One sound, or one object no larger than a 5-foot cube. Not both, and the image makes no noise.'),
('sp_poisonspray','Poison Spray','Poison Spray',0,'Save','Cantrips','conjuration','con','1d12',
 false,false,'10 feet','Instant','1 action',array['v','s'],null,
 array['druid','sorcerer','warlock','wizard'],
 '2d12 at 5th level, 3d12 at 11th, 4d12 at 17th.',
 'A puff of foul gas at something close enough to touch. A failed Constitution save takes 1d12 poison.'),
('sp_prestidigitation','Prestidigitation','Prestidigitation',0,'Utility','Cantrips','transmutation',null,null,
 false,false,'10 feet','Up to 1 hour','1 action',array['v','s'],null,
 array['bard','sorcerer','warlock','wizard'],
 'Up to three effects at once; a trivial one lasts an hour, the rest a round.',
 'The small tricks that mark somebody as trained: a spark, a smell, a clean shirt, a chilled drink, a trinket that lasts a moment.'),
('sp_rayoffrost','Ray of Frost','Ray of Frost',0,'Attack','Cantrips','evocation',null,'1d8',
 false,false,'60 feet','Instant','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'The target''s speed also drops by 10 feet until your next turn. 2d8 at 5th level, 3d8 at 11th, 4d8 at 17th.',
 'A beam of cold: a spell attack for 1d8 cold damage that leaves the target slowed.'),
('sp_shockinggrasp','Shocking Grasp','Shocking Grasp',0,'Attack','Cantrips','evocation',null,'1d8',
 false,false,'Touch','Instant','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'Advantage if the target is wearing metal armour. It cannot take reactions until its next turn.',
 'Lightning through a touch: a melee spell attack for 1d8 lightning that stops the target reacting.'),
('sp_truestrike','True Strike','True Strike',0,'Utility','Cantrips','divination',null,null,
 true,false,'30 feet','Up to 1 round','1 action',array['s'],null,
 array['bard','sorcerer','warlock','wizard'],
 'Costs your action this turn to improve one attack on the next, which is rarely worth it.',
 'A glimpse of one target''s defences: advantage on your first attack roll against it on your next turn.'),
('sp_alarm','Alarm','Alarm',1,'Utility','1st Circle','abjuration',null,null,
 false,true,'30 feet','8 hours','1 minute',array['v','s','m'],'a tiny bell and silver wire',
 array['ranger','wizard'],
 'Name the creatures it ignores when you cast it.',
 'A warded area up to 20 feet across that tells you - audibly, or only in your head - when something enters it.'),
('sp_burninghands','Burning Hands','Burning Hands',1,'Save','1st Circle','evocation','dex','3d6',
 false,false,'Self (15-foot cone)','Instant','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'Unattended flammable objects ignite. +1d6 per slot level above 1st.',
 'A sheet of flame from the fingertips. Everything in the cone makes a Dexterity save for 3d6 fire, half on a success.'),
('sp_charmperson','Charm Person','Charm Person',1,'Save','1st Circle','enchantment','wis',null,
 false,false,'30 feet','1 hour','1 action',array['v','s'],null,
 array['bard','druid','sorcerer','warlock','wizard'],
 'Advantage on the save if you or your allies are fighting it. It knows it was charmed when the spell ends. One more target per slot level above 1st.',
 'One humanoid that fails a Wisdom save treats you as a friendly acquaintance until the spell ends or you harm it.'),
('sp_colorspray','Color Spray','Color Spray',1,'Utility','1st Circle','illusion',null,null,
 false,false,'Self (15-foot cone)','1 round','1 action',array['v','s','m'],'a pinch of coloured sand',
 array['sorcerer','wizard'],
 'Roll 6d10: that many hit points of creatures are blinded, lowest current hit points first, ignoring any that cannot see. NOT damage - +2d10 to the pool per slot level above 1st.',
 'A dazzling spray of colour that blinds the weakest creatures in front of you until the end of your next turn.'),
('sp_comprehendlanguages','Comprehend Languages','Comprehend Languages',1,'Utility','1st Circle','divination',null,null,
 false,true,'Self','1 hour','1 action',array['v','s','m'],'a pinch of soot and salt',
 array['bard','sorcerer','warlock','wizard'],
 'Understanding only - it does not let you speak or write anything, and secret messages stay secret.',
 'Every spoken language you hear makes sense, and any writing you touch can be read.'),
('sp_disguiseself','Disguise Self','Disguise Self',1,'Utility','1st Circle','illusion',null,null,
 false,false,'Self','1 hour','1 action',array['v','s'],null,
 array['bard','sorcerer','wizard'],
 'Your height may change by up to a foot and your build must stay broadly the same. Touching it reveals it; a suspicious creature may Investigate against your save DC.',
 'You look, sound and dress like somebody else - an illusion only, so a hand passes straight through the change.'),
('sp_expeditiousretreat','Expeditious Retreat','Expeditious Retreat',1,'Utility','1st Circle','transmutation',null,null,
 true,false,'Self','Up to 10 minutes','1 bonus action',array['v','s'],null,
 array['sorcerer','warlock','wizard'],
 'Dash again as a bonus action on each of your turns while it lasts.',
 'You move at speed: the Dash action immediately, and again as a bonus action every turn after.'),
('sp_falselife','False Life','False Life',1,'Utility','1st Circle','necromancy',null,null,
 false,false,'Self','1 hour','1 action',array['v','s','m'],'a small amount of alcohol',
 array['sorcerer','wizard'],
 '1d4 + 4 TEMPORARY hit points - not healing, and not in `dice` for that reason. +5 per slot level above 1st.',
 'A brief necromantic shoring-up that leaves you harder to put down for an hour.'),
('sp_featherfall','Feather Fall','Feather Fall',1,'Utility','1st Circle','transmutation',null,null,
 false,false,'60 feet','1 minute','1 reaction',array['v','m'],'a small feather or piece of down',
 array['bard','sorcerer','wizard'],
 'Cast as a reaction when you or a creature within range falls. Up to five creatures.',
 'Falling creatures drop at 60 feet a round and land without harm.'),
('sp_fogcloud','Fog Cloud','Fog Cloud',1,'Utility','1st Circle','conjuration',null,null,
 true,false,'120 feet','Up to 1 hour','1 action',array['v','s'],null,
 array['druid','ranger','sorcerer','wizard'],
 'A 20-foot-radius sphere, 5 feet wider per slot level above 1st. Wind of 10 mph disperses it in 4 rounds.',
 'A bank of fog that blocks sight entirely for everyone, including you.'),
('sp_hideouslaughter','Hideous Laughter','Hideous Laughter',1,'Save','1st Circle','enchantment','wis',null,
 true,false,'30 feet','Up to 1 minute','1 action',array['v','s','m'],'tiny tarts and a feather',
 array['bard','wizard'],
 'A creature with Intelligence 4 or lower is unaffected. It saves again at the end of each of its turns, with advantage if it has taken damage since your last turn.',
 'One creature finds everything unbearably funny: a failed Wisdom save leaves it prone, incapacitated and unable to stand while it laughs.'),
('sp_identify','Identify','Identify',1,'Utility','1st Circle','divination',null,null,
 false,true,'Touch','Instant','1 minute',array['v','s','m'],'a pearl worth 100 gp and an owl feather',
 array['bard','wizard'],
 'It does not reveal a curse, and a creature touched instead reveals what spells are affecting it.',
 'An hour''s worth of study in a minute: what the item is, what it does, whether it needs attunement and how to use it.'),
('sp_illusoryscript','Illusory Script','Illusory Script',1,'Utility','1st Circle','illusion',null,null,
 false,true,'Touch','10 days','1 minute',array['s','m'],'lead-based ink worth 10 gp',
 array['bard','warlock','wizard'],
 'Truesight reads the real message. Name the creatures that can read it when you cast it.',
 'Writing that says one thing to you and the readers you choose, and something else entirely to everybody else.'),
('sp_jump','Jump','Jump',1,'Utility','1st Circle','transmutation',null,null,
 false,false,'Touch','1 minute','1 action',array['v','s','m'],'a grasshopper''s hind leg',
 array['druid','ranger','sorcerer','wizard'],
 'Distance only - it does not change how far the creature can move in a turn.',
 'One creature''s jump distance is tripled for a minute.'),
('sp_longstrider','Longstrider','Longstrider',1,'Utility','1st Circle','transmutation',null,null,
 false,false,'Touch','1 hour','1 action',array['v','s','m'],'a pinch of dirt',
 array['bard','druid','ranger','wizard'],
 'One more creature per slot level above 1st.',
 'A creature''s speed goes up by 10 feet for an hour.'),
('sp_magearmor','Mage Armor','Mage Armor',1,'Utility','1st Circle','abjuration',null,null,
 false,false,'Touch','8 hours','1 action',array['v','s','m'],'a piece of cured leather',
 array['sorcerer','wizard'],
 'The target''s AC becomes 13 + its Dexterity modifier. Ends if it puts armour on, and you may dismiss it. NOT APPLIED BY THE ENGINE - the grant vocabulary can floor an AC but cannot say "13 plus Dexterity".',
 'A shell of force around an unarmoured creature, standing in for armour it is not wearing.'),
('sp_magicmissile','Magic Missile','Magic Missile',1,'Utility','1st Circle','evocation',null,'3d4+3',
 false,false,'120 feet','Instant','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'THREE DARTS THAT CANNOT MISS: 1d4+1 force each, split between targets as you like. No attack roll and no save, which is why this is not an Attack. One more dart per slot level above 1st.',
 'Three darts of force that strike whatever you point them at, without fail.'),
('sp_shield','Shield','Shield',1,'Utility','1st Circle','abjuration',null,null,
 false,false,'Self','1 round','1 reaction',array['v','s'],null,
 array['sorcerer','wizard'],
 'Cast as a reaction when you are hit or targeted by Magic Missile. +5 AC until the start of your next turn, INCLUDING against the triggering attack, and Magic Missile does nothing to you.',
 'A barrier of force that snaps up in the instant before a blow lands.'),
('sp_silentimage','Silent Image','Silent Image',1,'Utility','1st Circle','illusion',null,null,
 true,false,'60 feet','Up to 10 minutes','1 action',array['v','s','m'],'a bit of fleece',
 array['bard','sorcerer','wizard'],
 'Silent, and physically insubstantial - it fails any test by touch. Investigation against your save DC sees through it.',
 'A visual illusion up to 15 feet across that you can move about with an action.'),
('sp_sleep','Sleep','Sleep',1,'Utility','1st Circle','enchantment',null,null,
 false,false,'90 feet','1 minute','1 action',array['v','s','m'],'a pinch of sand or rose petals',
 array['bard','sorcerer','wizard'],
 'Roll 5d8: that many hit points of creatures fall unconscious, lowest current hit points first. NOT damage. The undead and anything immune to being charmed ignore it. +2d8 to the pool per slot level above 1st.',
 'A wave of drowsiness that takes the weakest first and drops them where they stand.'),
('sp_thunderwave','Thunderwave','Thunderwave',1,'Save','1st Circle','evocation','con','2d8',
 false,false,'Self (15-foot cube)','Instant','1 action',array['v','s'],null,
 array['bard','druid','sorcerer','wizard'],
 'A failed save is also pushed 10 feet away. Unsecured objects are pushed too, and the boom carries 300 feet. +1d8 per slot level above 1st.',
 'A wave of force out from you: everything in the cube makes a Constitution save for 2d8 thunder, half on a success.'),
('sp_unseenservant','Unseen Servant','Unseen Servant',1,'Utility','1st Circle','conjuration',null,null,
 false,true,'60 feet','1 hour','1 action',array['v','s','m'],'a piece of string and a bit of wood',
 array['bard','warlock','wizard'],
 'AC 10, 1 hit point, Strength 2. It cannot attack, and it vanishes if it takes any damage or strays more than 60 feet from you.',
 'An invisible servant that fetches, cleans, mends, carries and serves, one simple task at a time.')
on conflict (key) where game_id is null do update set
  name=excluded.name, roll_name=excluded.roll_name, level=excluded.level,
  cast_type=excluded.cast_type, category=excluded.category, school=excluded.school,
  save_ability=excluded.save_ability, dice=excluded.dice,
  concentration=excluded.concentration, ritual=excluded.ritual,
  range=excluded.range, duration=excluded.duration, casting_time=excluded.casting_time,
  components=excluded.components, material=excluded.material, classes=excluded.classes,
  special_text=excluded.special_text, description=excluded.description;

update public.spells
   set description = 'Every creature in a 20-foot-radius sphere makes a Dexterity save for 8d6 fire damage, half on a success. Unattended flammable objects in the area catch fire.'
 where game_id is null and key = 'sp_fireball';

update public.spells
   set description = 'A 30-foot aura around you. While it holds, you and your allies inside resist necrotic damage, and anyone at 0 hit points regains 1 at the start of their turn.'
 where game_id is null and key = 'sp_auraoflife';
