-- 162. THE WIZARD LIST: SECOND AND THIRD CIRCLE.
--
-- 161 did the cantrips and first circle and left 101. This is 38 of
-- them and finishes both levels: 27 of 27 at second, 27 of 27 at third.
-- Same contract as 161 and 102-104: mechanical values read off the
-- published SRD, every description written for this catalogue.
--
-- THE DICE COLUMN KEEPS ITS DISCIPLINE - 158's rule, and this pair of
-- levels earns it. Scorching Ray is THREE attack rolls of 2d6, so the
-- dice are ONE ray and the special text says there are three; an engine
-- rolling 6d6 once would be rolling a spell nobody casts, since three
-- rays can take three targets and miss separately.
--
-- Full reasoning in
-- supabase/migrations/162_the_wizard_list_second_and_third.sql.

insert into spells
  (key, name, roll_name, level, cast_type, category, school, save_ability, dice,
   concentration, ritual, range, duration, casting_time, components, material,
   classes, special_text, description)
values
('sp_alterself','Alter Self','Alter Self',2,'Utility','2nd Circle','transmutation',null,null,
 true,false,'Self','Up to 1 hour','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'Three options: breathe underwater and swim, change your appearance, or grow a natural weapon that counts as magical and deals 1d6.',
 'You remake your own body - gills, a different face, or a claw or horn that was not there a moment ago.'),
('sp_blur','Blur','Blur',2,'Utility','2nd Circle','illusion',null,null,
 true,false,'Self','Up to 1 minute','1 action',array['v'],null,
 array['sorcerer','wizard'],
 'No help against a creature with blindsight or truesight, or one that does not rely on sight.',
 'Your outline swims and doubles: attacks against you have disadvantage.'),
('sp_darkness','Darkness','Darkness',2,'Utility','2nd Circle','evocation',null,null,
 true,false,'60 feet','Up to 10 minutes','1 action',array['v','m'],'bat fur and a drop of pitch or coal',
 array['sorcerer','warlock','wizard'],
 'Darkvision cannot see through it and ordinary light cannot illuminate it. Cast on an object to carry it, or cover the object to block it.',
 'A 15-foot sphere of magical darkness that nothing sees into, including you.'),
('sp_darkvisionspell','Darkvision','Darkvision',2,'Utility','2nd Circle','transmutation',null,null,
 false,false,'Touch','8 hours','1 action',array['v','s','m'],'dried carrot or an agate',
 array['druid','ranger','sorcerer','wizard'],
 'Keyed as `sp_darkvisionspell` because the species trait of the same name is a different thing.',
 'One creature sees 60 feet in the dark for eight hours.'),
('sp_detectthoughts','Detect Thoughts','Detect Thoughts',2,'Utility','2nd Circle','divination',null,null,
 true,false,'Self','Up to 1 minute','1 action',array['v','s','m'],'a copper piece',
 array['bard','sorcerer','wizard'],
 'Probing deeper lets the target make a Wisdom save; on a success it notices you and the spell ends.',
 'Surface thoughts from any creature within 30 feet, and deeper ones if you push and it does not notice.'),
('sp_enlargereduce','Enlarge/Reduce','Enlarge/Reduce',2,'Utility','2nd Circle','transmutation',null,null,
 true,false,'30 feet','Up to 1 minute','1 action',array['v','s','m'],'a pinch of powdered iron',
 array['sorcerer','wizard'],
 'An unwilling target makes a Constitution save. Enlarged: one size up, advantage on Strength checks and saves, +1d4 weapon damage. Reduced: the reverse.',
 'One creature or object doubles or halves in every dimension, and its weight changes eightfold to match.'),
('sp_flamingsphere','Flaming Sphere','Flaming Sphere',2,'Save','2nd Circle','conjuration','dex','2d6',
 true,false,'60 feet','Up to 1 minute','1 action',array['v','s','m'],'tallow, brimstone and powdered iron',
 array['druid','wizard'],
 'Anything ending its turn within 5 feet saves for 2d6 fire, half on a success. Move the sphere 30 feet as a bonus action; it can be rammed into a creature. +1d6 per slot level above 2nd.',
 'A burning sphere five feet across that you roll around the battlefield.'),
('sp_gustofwind','Gust of Wind','Gust of Wind',2,'Save','2nd Circle','evocation','str',null,
 true,false,'Self (60-foot line)','Up to 1 minute','1 action',array['v','s','m'],'a legume seed',
 array['druid','sorcerer','wizard'],
 'A failed Strength save is pushed 15 feet away. The line is difficult terrain against the wind, and it disperses gas and snuffs flames.',
 'A sustained blast of wind down a 60-foot line, shoving anything that cannot brace against it.'),
('sp_invisibility','Invisibility','Invisibility',2,'Utility','2nd Circle','illusion',null,null,
 true,false,'Touch','Up to 1 hour','1 action',array['v','s','m'],'an eyelash in gum arabic',
 array['bard','sorcerer','warlock','wizard'],
 'Ends the moment the target attacks or casts a spell. Anything it is carrying is invisible too. One more creature per slot level above 2nd.',
 'A creature and its gear vanish from sight until it does something hostile.'),
('sp_knock','Knock','Knock',2,'Utility','2nd Circle','transmutation',null,null,
 false,false,'60 feet','Instant','1 action',array['v'],null,
 array['bard','sorcerer','wizard'],
 'Loud: a knock audible 300 feet away, which is the cost of using it instead of a lockpick.',
 'One lock, bar, door, lid or set of manacles opens - or an arcane seal is suppressed for ten minutes.'),
('sp_levitate','Levitate','Levitate',2,'Save','2nd Circle','transmutation','con',null,
 true,false,'60 feet','Up to 10 minutes','1 action',array['v','s','m'],'a leather loop or golden wire',
 array['sorcerer','wizard'],
 'An unwilling target saves. Up to 500 pounds. Move it 20 feet vertically on your turn; it cannot move horizontally except by pushing off something.',
 'One creature or object rises straight up and stays there, out of reach and out of the fight.'),
('sp_magicmouth','Magic Mouth','Magic Mouth',2,'Utility','2nd Circle','illusion',null,null,
 false,true,'30 feet','Until dispelled','1 minute',array['v','s','m'],'jade dust worth 10 gp',
 array['bard','wizard'],
 'The message is up to 25 words and takes up to 10 minutes to deliver. Set the trigger when you cast it.',
 'A mouth appears on an object and speaks a message you left there, when the condition you named is met.'),
('sp_magicweapon','Magic Weapon','Magic Weapon',2,'Utility','2nd Circle','transmutation',null,null,
 true,false,'Touch','Up to 1 hour','1 bonus action',array['v','s'],null,
 array['paladin','wizard'],
 'A +1 weapon, counting as magical. +2 at 4th-level slot, +3 at 6th. 143''s qualifier means this is what gets a party past a werewolf.',
 'A nonmagical weapon becomes magical, and better: +1 to hit and damage for an hour.'),
('sp_mirrorimage','Mirror Image','Mirror Image',2,'Utility','2nd Circle','illusion',null,null,
 false,false,'Self','1 minute','1 action',array['v','s'],null,
 array['sorcerer','warlock','wizard'],
 'Three duplicates. An attack aimed at you may hit one instead - AC 10 + your Dexterity modifier - and a hit destroys that duplicate.',
 'Three illusory copies of you shuffle and swap, and an attacker has to guess which one is real.'),
('sp_mistystep','Misty Step','Misty Step',2,'Utility','2nd Circle','conjuration',null,null,
 false,false,'Self','Instant','1 bonus action',array['v'],null,
 array['sorcerer','warlock','wizard'],
 'A bonus action, so you can still act. You must be able to see where you are going.',
 'You vanish in silver mist and reappear up to 30 feet away.'),
('sp_rayofenfeeblement','Ray of Enfeeblement','Ray of Enfeeblement',2,'Attack','2nd Circle','necromancy',null,null,
 true,false,'60 feet','Up to 1 minute','1 action',array['v','s'],null,
 array['warlock','wizard'],
 'A hit halves the damage of its Strength-based weapon attacks. It saves at the end of each of its turns to end the effect. No damage of its own.',
 'A black beam: on a hit the target is enfeebled and its blows land soft.'),
('sp_scorchingray','Scorching Ray','Scorching Ray',2,'Attack','2nd Circle','evocation',null,'2d6',
 false,false,'120 feet','Instant','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'THREE RAYS, each its own attack roll for 2d6 fire - the dice here are ONE ray. Split them between targets as you like. One more ray per slot level above 2nd.',
 'Three rays of fire, each aimed and rolled separately, at one target or several.'),
('sp_seeinvisibility','See Invisibility','See Invisibility',2,'Utility','2nd Circle','divination',null,null,
 false,false,'Self','1 hour','1 action',array['v','s','m'],'talc and silver powder',
 array['bard','sorcerer','wizard'],
 'You also see into the Ethereal Plane, where its creatures appear as ghostly shapes.',
 'Invisible creatures and objects look ordinary to you for an hour.'),
('sp_shatter','Shatter','Shatter',2,'Save','2nd Circle','evocation','con','3d8',
 false,false,'60 feet','Instant','1 action',array['v','s','m'],'a chip of mica',
 array['bard','sorcerer','warlock','wizard'],
 'A 10-foot-radius sphere. Creatures made of inorganic material have disadvantage on the save; unattended objects take the damage outright. +1d8 per slot level above 2nd.',
 'A painfully loud ringing: everything in the sphere makes a Constitution save for 3d8 thunder, half on a success.'),
('sp_spiderclimb','Spider Climb','Spider Climb',2,'Utility','2nd Circle','transmutation',null,null,
 true,false,'Touch','Up to 1 hour','1 action',array['v','s','m'],'a drop of bitumen and a spider',
 array['sorcerer','warlock','wizard'],
 'The target gains a climbing speed equal to its walking speed.',
 'One creature walks up walls and across ceilings with its hands free.'),
('sp_suggestion','Suggestion','Suggestion',2,'Save','2nd Circle','enchantment','wis',null,
 true,false,'30 feet','Up to 8 hours','1 action',array['v','m'],'a snake''s tongue and honeycomb or oil',
 array['bard','sorcerer','warlock','wizard'],
 'The course of action must sound reasonable and must not be obviously harmful. The spell ends if you or your allies harm the target.',
 'One creature that fails a Wisdom save pursues a reasonable-sounding course of action you describe in a sentence or two.'),
('sp_web','Web','Web',2,'Save','2nd Circle','conjuration','dex',null,
 true,false,'60 feet','Up to 1 hour','1 action',array['v','s','m'],'a bit of spiderweb',
 array['sorcerer','wizard'],
 'A 20-foot cube of difficult terrain. A failed Dexterity save is restrained; a restrained creature may escape with a Strength check against your save DC. The webs burn: 2d4 fire to anything in them when lit.',
 'Thick webs fill the space and hold fast whatever walks into them.'),
('sp_blink','Blink','Blink',3,'Utility','3rd Circle','transmutation',null,null,
 false,false,'Self','1 minute','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'Roll a d20 at the end of each of your turns: on 11 or higher you vanish to the Ethereal Plane and return at the start of your next turn, up to 10 feet from where you left.',
 'You flicker half out of the world and back, impossible to touch for as long as you are gone.'),
('sp_counterspell','Counterspell','Counterspell',3,'Utility','3rd Circle','abjuration',null,null,
 false,false,'60 feet','Instant','1 reaction',array['s'],null,
 array['sorcerer','warlock','wizard'],
 'A REACTION, taken when you see a creature casting. A spell of 3rd level or lower simply fails; anything higher needs an ability check with your casting ability against DC 10 + the spell''s level. Use a higher slot to raise the automatic threshold.',
 'You interrupt a spell as it is being cast and it does not happen.'),
('sp_fear','Fear','Fear',3,'Save','3rd Circle','illusion','wis',null,
 true,false,'Self (30-foot cone)','Up to 1 minute','1 action',array['v','s','m'],'a white feather or the heart of a hen',
 array['bard','sorcerer','warlock','wizard'],
 'A failed Wisdom save drops whatever it is holding and is frightened, and must Dash away from you while it can see you. It saves again at the end of each of its turns, and only if it can see nothing of you.',
 'Everything in the cone sees what frightens it most and runs.'),
('sp_fly','Fly','Fly',3,'Utility','3rd Circle','transmutation',null,null,
 true,false,'Touch','Up to 10 minutes','1 action',array['v','s','m'],'a wing feather',
 array['sorcerer','warlock','wizard'],
 'A 60-foot flying speed. If the spell ends while the target is aloft, it falls. One more creature per slot level above 3rd.',
 'One creature flies for ten minutes, which is long enough to matter and short enough to be frightening.'),
('sp_gaseousform','Gaseous Form','Gaseous Form',3,'Utility','3rd Circle','transmutation',null,null,
 true,false,'Touch','Up to 1 hour','1 action',array['v','s','m'],'a bit of gauze and a wisp of smoke',
 array['sorcerer','warlock','wizard'],
 'Resistance to nonmagical damage, advantage on Strength, Dexterity and Constitution saves, and it can pass through any opening air can. It cannot attack, cast or speak, and it drops everything.',
 'A willing creature becomes a cloud of mist that drifts through cracks at 10 feet a round.'),
('sp_haste','Haste','Haste',3,'Utility','3rd Circle','transmutation',null,null,
 true,false,'30 feet','Up to 1 minute','1 action',array['v','s','m'],'a shaving of liquorice root',
 array['sorcerer','wizard'],
 'Double speed, +2 AC, advantage on Dexterity saves, and one extra action each turn limited to Attack (one attack), Dash, Disengage, Hide or Use an Object. WHEN IT ENDS the target loses its next turn entirely.',
 'One willing creature moves and acts at twice the pace - and pays for it the moment the spell drops.'),
('sp_hypnoticpattern','Hypnotic Pattern','Hypnotic Pattern',3,'Save','3rd Circle','illusion','wis',null,
 true,false,'120 feet','Up to 1 minute','1 action',array['s','m'],'a pinch of glittering powder',
 array['bard','sorcerer','warlock','wizard'],
 'A 30-foot cube. A failed Wisdom save is charmed, incapacitated and has a speed of 0. Any damage, or an ally using its action to shake it, ends it for that creature.',
 'A drifting pattern of colour that holds everyone who looks at it still and staring.'),
('sp_lightningbolt','Lightning Bolt','Lightning Bolt',3,'Save','3rd Circle','evocation','dex','8d6',
 false,false,'Self (100-foot line)','Instant','1 action',array['v','s','m'],'fur and a crystal rod',
 array['sorcerer','wizard'],
 'A 100-foot line, 5 feet wide - everything in it saves, not just the first target. Unattended flammable objects ignite. +1d6 per slot level above 3rd.',
 'A stroke of lightning straight out from you: a Dexterity save for 8d6 lightning, half on a success.'),
('sp_majorimage','Major Image','Major Image',3,'Utility','3rd Circle','illusion',null,null,
 true,false,'120 feet','Up to 10 minutes','1 action',array['v','s','m'],'a bit of fleece',
 array['bard','sorcerer','warlock','wizard'],
 'Sound, smell and temperature as well as sight, but still no substance. Investigation against your save DC sees through it. Cast with a 6th-level slot and it lasts until dispelled.',
 'An illusion up to 20 feet across that can be heard and smelled as well as seen.'),
('sp_nondetection','Nondetection','Nondetection',3,'Utility','3rd Circle','abjuration',null,null,
 false,false,'Touch','8 hours','1 action',array['v','s','m'],'a pinch of diamond dust worth 25 gp',
 array['bard','ranger','wizard'],
 'Hides it from divination magic and scrying sensors alike.',
 'One creature, place or object cannot be found by magic for eight hours.'),
('sp_sleetstorm','Sleet Storm','Sleet Storm',3,'Utility','3rd Circle','conjuration',null,null,
 true,false,'150 feet','Up to 1 minute','1 action',array['v','s','m'],'a pinch of dust and a few drops of water',
 array['druid','sorcerer','wizard'],
 'A 40-foot cylinder: difficult terrain, heavily obscured, open flames out. A creature entering or starting there makes a Dexterity save or falls prone; one concentrating makes a Constitution save or loses it.',
 'Freezing rain and sleet over a wide area, which puts out the lights and puts people on the ground.'),
('sp_slow','Slow','Slow',3,'Save','3rd Circle','transmutation','wis',null,
 true,false,'120 feet','Up to 1 minute','1 action',array['v','s','m'],'a drop of molasses',
 array['sorcerer','wizard'],
 'Up to six creatures in a 40-foot cube. A failed Wisdom save halves speed, costs 2 AC and Dexterity saves, allows no reactions, and limits them to an action OR a bonus action each turn. They save again at the end of each of their turns.',
 'Up to six creatures move and think at half pace, and can only do one thing at a time.'),
('sp_stinkingcloud','Stinking Cloud','Stinking Cloud',3,'Save','3rd Circle','conjuration','con',null,
 true,false,'90 feet','Up to 1 minute','1 action',array['v','s','m'],'a rotten egg or several skunk cabbage leaves',
 array['bard','sorcerer','wizard'],
 'A 20-foot-radius sphere of heavily obscuring gas. A creature starting its turn there makes a Constitution save or spends its action retching. Wind of 10 mph disperses it in 4 rounds.',
 'A cloud of stench so thick that anything inside spends its turn being sick instead of fighting.'),
('sp_tinyhut','Tiny Hut','Tiny Hut',3,'Utility','3rd Circle','evocation',null,null,
 false,true,'Self (10-foot-radius hemisphere)','8 hours','1 minute',array['v','s','m'],'a small crystal bead',
 array['bard','wizard'],
 'Nine creatures fit. Nothing passes the dome in either direction - no spells, no missiles - and a creature that steps out cannot get back in. You must stay inside or it ends.',
 'An immobile dome of force that shelters a small party for a night.'),
('sp_vampirictouch','Vampiric Touch','Vampiric Touch',3,'Attack','3rd Circle','necromancy',null,'3d6',
 true,false,'Self','Up to 1 minute','1 action',array['v','s'],null,
 array['warlock','wizard'],
 'A melee spell attack each turn while it lasts. You regain HALF the necrotic damage dealt, rounded down - the engine rolls the damage and the healing is the DM''s to apply. +1d6 per slot level above 3rd.',
 'A withering touch for 3d6 necrotic, and half of what it takes comes back to you.'),
('sp_waterbreathing','Water Breathing','Water Breathing',3,'Utility','3rd Circle','transmutation',null,null,
 false,true,'30 feet','24 hours','1 action',array['v','s','m'],'a short reed or piece of straw',
 array['druid','ranger','sorcerer','wizard'],
 'Up to ten willing creatures, and it does not take away their ability to breathe air.',
 'Ten creatures breathe underwater for a day.')
on conflict (key) where game_id is null do update set
  name=excluded.name, roll_name=excluded.roll_name, level=excluded.level,
  cast_type=excluded.cast_type, category=excluded.category, school=excluded.school,
  save_ability=excluded.save_ability, dice=excluded.dice,
  concentration=excluded.concentration, ritual=excluded.ritual,
  range=excluded.range, duration=excluded.duration, casting_time=excluded.casting_time,
  components=excluded.components, material=excluded.material, classes=excluded.classes,
  special_text=excluded.special_text, description=excluded.description;

update public.spells
   set special_text = 'THE SAVE DEPENDS ON THE GLYPH, which is why no ability is named: Death, Pain and Stunning are Constitution; Fear, Insanity and Sleep are Wisdom; Hopelessness is Charisma; Discord is Constitution. Choose the glyph when you inscribe it, and the DM calls for that save.'
 where game_id is null and key = 'sp_symbol' and special_text is null;
