-- 163. THE WIZARD LIST: FOURTH AND FIFTH CIRCLE.
--
-- 25 more, finishing both levels. 38 left after this, all 6th and
-- above. Same contract as 161, 162 and 102-104: mechanical values read
-- off the published SRD, every description written here.
--
-- STONESKIN IS 143'S QUALIFIER FROM THE OTHER SIDE - resistance to
-- b/p/s from NONMAGICAL attacks, the exact condition 143 built
-- resist.slashing.nonmagical for. Not wired as a grant: whether a
-- concentration spell's grant should end when concentration breaks is a
-- rule nobody has written. The text says it and the DM applies it.
--
-- CONTACT OTHER PLANE IS A SAVE THE CASTER MAKES against a FIXED DC 15,
-- not anybody's spell save DC, so marking it `Save` would print the
-- wrong number with total confidence. Utility, with the roll in the
-- text - the same decision 136 made about the Shrieker.
--
-- Full reasoning in
-- supabase/migrations/163_the_wizard_list_fourth_and_fifth.sql.

insert into spells
  (key, name, roll_name, level, cast_type, category, school, save_ability, dice,
   concentration, ritual, range, duration, casting_time, components, material,
   classes, special_text, description)
values
('sp_blight','Blight','Blight',4,'Save','4th Circle','necromancy','con','8d8',
 false,false,'30 feet','Instant','1 action',array['v','s'],null,
 array['druid','sorcerer','warlock','wizard'],
 'The undead and constructs are unaffected. A plant creature has disadvantage and takes maximum damage; a nonmagical plant withers outright. +1d8 per slot level above 4th.',
 'The moisture is drawn out of one living thing: a Constitution save for 8d8 necrotic, half on a success.'),
('sp_confusion','Confusion','Confusion',4,'Save','4th Circle','enchantment','wis',null,
 true,false,'90 feet','Up to 1 minute','1 action',array['v','s','m'],'three nut shells',
 array['bard','druid','sorcerer','wizard'],
 'A 10-foot-radius sphere, 5 feet wider per slot level above 4th. A failed Wisdom save rolls a d10 each turn: wander, do nothing, attack at random, or act normally. It saves again at the end of each of its turns.',
 'Everything in the sphere that fails a Wisdom save stops acting sensibly and starts acting at random.'),
('sp_conjureminorelementals','Conjure Minor Elementals','Conjure Minor Elementals',4,'Utility','4th Circle','conjuration',null,null,
 true,false,'90 feet','Up to 1 hour','1 minute',array['v','s'],null,
 array['druid','wizard'],
 'Choose the spread: one CR 2, two CR 1, four CR 1/2 or eight CR 1/4. THE DM CHOOSES WHAT ARRIVES, and if your concentration breaks they stop obeying you.',
 'Elemental spirits take form and fight for you, in numbers inversely proportional to how dangerous each one is.'),
('sp_dimensiondoor','Dimension Door','Dimension Door',4,'Utility','4th Circle','conjuration',null,null,
 false,false,'500 feet','Instant','1 action',array['v'],null,
 array['bard','sorcerer','warlock','wizard'],
 'You may bring one willing creature of your size or smaller that is within 5 feet. Arriving inside something solid takes 4d6 force and puts you back where you started.',
 'You step out of here and into a spot up to 500 feet away, described or simply pictured.'),
('sp_greaterinvisibility','Greater Invisibility','Greater Invisibility',4,'Utility','4th Circle','illusion',null,null,
 true,false,'Touch','Up to 1 minute','1 action',array['v','s'],null,
 array['bard','sorcerer','wizard'],
 'Unlike Invisibility, attacking and casting do NOT end it - which is the whole reason it is two circles higher.',
 'A creature is invisible for the minute, and stays invisible while it fights.'),
('sp_hallucinatoryterrain','Hallucinatory Terrain','Hallucinatory Terrain',4,'Utility','4th Circle','illusion',null,null,
 false,false,'300 feet','24 hours','10 minutes',array['v','s','m'],'a stone, a twig and a bit of green plant',
 array['bard','druid','warlock','wizard'],
 'Structures, equipment and creatures are not disguised. Touch reveals it, and Investigation against your save DC sees through it.',
 'A 150-foot cube of open ground looks, sounds and smells like different ground entirely.'),
('sp_icestorm','Ice Storm','Ice Storm',4,'Save','4th Circle','evocation','dex','2d8',
 false,false,'300 feet','Instant','1 action',array['v','s','m'],'a pinch of dust and a few drops of water',
 array['druid','sorcerer','wizard'],
 'A 20-foot-radius cylinder. TWO DAMAGE TYPES: 2d8 bludgeoning plus 4d6 cold on a failed save, half on a success - the `dice` column holds the bludgeoning half only. The ground becomes difficult terrain. +1d8 bludgeoning per slot level above 4th.',
 'Hail the size of fists over a wide circle, and the ground left treacherous behind it.'),
('sp_polymorph','Polymorph','Polymorph',4,'Save','4th Circle','transmutation','wis',null,
 true,false,'60 feet','Up to 1 hour','1 action',array['v','s','m'],'a caterpillar cocoon',
 array['bard','druid','sorcerer','wizard'],
 'An unwilling target saves. The new form is a beast whose CR is no higher than the target''s level or CR. It keeps its alignment and personality, gains the beast''s statistics, and reverts when it drops to 0 of the beast''s hit points. NOT WIRED: 123 can instantiate a statblock, and nothing connects a spell to that.',
 'One creature becomes a beast - with the beast''s body, hit points and limits - until the spell ends or the beast is dropped.'),
('sp_stoneskin','Stoneskin','Stoneskin',4,'Utility','4th Circle','abjuration',null,null,
 true,false,'Touch','Up to 1 hour','1 action',array['v','s','m'],'diamond dust worth 100 gp',
 array['druid','ranger','sorcerer','wizard'],
 'Resistance to bludgeoning, piercing and slashing FROM NONMAGICAL ATTACKS - 143''s exact qualifier, and the vocabulary to say it exists (resist.slashing.nonmagical). NOT WIRED as a grant: whether a concentration spell''s grant should end with concentration is a rule nobody has written. The DM applies it.',
 'A willing creature''s skin turns to stone: ordinary weapons do half damage, enchanted ones do not care.'),
('sp_walloffire','Wall of Fire','Wall of Fire',4,'Save','4th Circle','evocation','dex','5d8',
 true,false,'120 feet','Up to 1 minute','1 action',array['v','s','m'],'a small piece of phosphorus',
 array['druid','sorcerer','wizard'],
 'A wall 60 feet long, 20 high and 1 thick, or a ring 20 feet across. ONE SIDE ONLY is hot - you choose which when you cast it - and anything ending its turn on that side or inside the wall saves. +1d8 per slot level above 4th.',
 'A sheet of flame that burns on the side you name: a Dexterity save for 5d8 fire, half on a success.'),
('sp_animateobjects','Animate Objects','Animate Objects',5,'Utility','5th Circle','transmutation',null,null,
 true,false,'120 feet','Up to 1 minute','1 action',array['v','s'],null,
 array['bard','sorcerer','wizard'],
 'Up to ten Small or smaller objects, or fewer and larger - a Medium counts as two, a Large as four, a Huge as eight. They act on your turn when you command them as a bonus action. Two more objects per slot level above 5th.',
 'Furniture, statuary and loose weapons stand up and fight for you.'),
('sp_cloudkill','Cloudkill','Cloudkill',5,'Save','5th Circle','conjuration','con','5d8',
 true,false,'120 feet','Up to 10 minutes','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'A 20-foot-radius sphere of heavily obscuring fog that moves 10 feet away from you each turn. Anything starting its turn inside saves. It sinks: it fills low ground and pours down holes. +1d8 per slot level above 5th.',
 'A fog of poison that rolls slowly across the ground and kills what it passes over.'),
('sp_coneofcold','Cone of Cold','Cone of Cold',5,'Save','5th Circle','evocation','con','8d8',
 false,false,'Self (60-foot cone)','Instant','1 action',array['v','s','m'],'a small crystal or glass cone',
 array['sorcerer','wizard'],
 'A creature killed by this becomes a frozen statue until it thaws. +1d8 per slot level above 5th.',
 'A blast of freezing air: everything in the cone makes a Constitution save for 8d8 cold, half on a success.'),
('sp_conjureelemental','Conjure Elemental','Conjure Elemental',5,'Utility','5th Circle','conjuration',null,null,
 true,false,'90 feet','Up to 1 hour','1 minute',array['v','s','m'],'burning incense, soft clay, sulphur and phosphorus, or water and sand',
 array['druid','wizard'],
 'CR 5 or lower, and one CR higher per slot level above 5th. THE DM CHOOSES WHICH ONE. If your concentration breaks it stops obeying and may turn on you.',
 'An elemental of the kind matching the material you burned, bound to your orders for as long as you hold it.'),
('sp_contactotherplane','Contact Other Plane','Contact Other Plane',5,'Utility','5th Circle','divination',null,null,
 false,true,'Self','1 minute','1 minute',array['v'],null,
 array['warlock','wizard'],
 'A SAVE YOU MAKE, against a FIXED DC 15 - not your own spell save DC, which is why this is not marked Save. Fail and take 6d6 psychic and be insane until a long rest. Succeed and ask up to five questions, answered in one word each.',
 'You reach for something on another plane and ask it questions, at the risk of your own mind.'),
('sp_creation','Creation','Creation',5,'Utility','5th Circle','illusion',null,null,
 false,false,'30 feet','Special','1 minute',array['v','s','m'],'a tiny piece of matter of the same kind',
 array['sorcerer','wizard'],
 'A 5-foot cube, one more foot per slot level above 5th. HOW LONG IT LASTS DEPENDS ON THE MATERIAL: vegetable matter a day, stone or crystal 12 hours, precious metals an hour, gems 10 minutes, adamantine or mithral a minute.',
 'Matter condenses out of shadow into something real enough to use, until it is not.'),
('sp_dominateperson','Dominate Person','Dominate Person',5,'Save','5th Circle','enchantment','wis',null,
 true,false,'60 feet','Up to 1 minute','1 action',array['v','s'],null,
 array['bard','sorcerer','wizard'],
 'A failed Wisdom save is charmed and takes your orders; spend an action to take direct control. It saves again each time it takes damage. Duration climbs with the slot: 10 minutes at 6th, an hour at 7th, eight hours at 8th.',
 'One humanoid does as you tell it, and will do it precisely if you spend the action to steer.'),
('sp_dream','Dream','Dream',5,'Utility','5th Circle','illusion',null,null,
 false,false,'Special','8 hours','1 minute',array['v','s','m'],'a handful of sand, ink and a quill',
 array['bard','warlock','wizard'],
 'The target must be on the same plane. If you make the messenger a nightmare it makes a Wisdom save or gains no benefit from the rest and takes 3d6 psychic on waking.',
 'You or a willing messenger enter a sleeping creature''s dream and talk to it there.'),
('sp_holdmonster','Hold Monster','Hold Monster',5,'Save','5th Circle','enchantment','wis',null,
 true,false,'90 feet','Up to 1 minute','1 action',array['v','s','m'],'a straight piece of iron',
 array['bard','sorcerer','warlock','wizard'],
 'Any creature except the undead - which is the difference from Hold Person. A failed Wisdom save is paralysed and saves again at the end of each of its turns. One more target per slot level above 5th.',
 'One creature of any kind freezes where it stands until it shakes the spell off.'),
('sp_mislead','Mislead','Mislead',5,'Utility','5th Circle','illusion',null,null,
 true,false,'Self','Up to 1 hour','1 action',array['s'],null,
 array['bard','wizard'],
 'You may see and hear through the double''s senses as a reaction, and while you do you are blind and deaf to your own. The double can go up to 500 feet from you.',
 'You turn invisible and an illusory double of you walks off, talking and gesturing as you direct.'),
('sp_modifymemory','Modify Memory','Modify Memory',5,'Save','5th Circle','enchantment','wis',null,
 true,false,'30 feet','Up to 1 minute','1 action',array['v','s'],null,
 array['bard','wizard'],
 'A failed Wisdom save leaves it charmed and open to having one memory reshaped. Reach further back with a higher slot: 7 days at 6th, 30 at 7th, a year at 8th, any time at 9th. Damage ends the spell and leaves the memory unaltered.',
 'One creature''s memory of the last day is rewritten to whatever you describe.'),
('sp_seeming','Seeming','Seeming',5,'Save','5th Circle','illusion','cha',null,
 false,false,'30 feet','8 hours','1 action',array['v','s'],null,
 array['bard','sorcerer','wizard'],
 'An unwilling creature saves. Illusion only - it changes nothing about what anyone can do, and touch reveals it. Investigation against your save DC sees through it.',
 'Any number of creatures you can see look like somebody else, clothes and all, for eight hours.'),
('sp_telekinesis','Telekinesis','Telekinesis',5,'Utility','5th Circle','transmutation',null,null,
 true,false,'60 feet','Up to 10 minutes','1 action',array['v','s'],null,
 array['sorcerer','wizard'],
 'A creature up to Huge may be moved 30 feet a turn if it loses a Strength contest against your casting ability check. Objects up to 1,000 pounds move freely.',
 'You move creatures and objects at a distance by will alone, one action at a time.'),
('sp_teleportationcircle','Teleportation Circle','Teleportation Circle',5,'Utility','5th Circle','conjuration',null,null,
 false,false,'10 feet','1 round','1 minute',array['v','m'],'rare chalks and inks worth 50 gp, consumed',
 array['bard','sorcerer','wizard'],
 'You must know the destination''s sigil sequence. The circle lasts one round, so anything going through goes immediately.',
 'A ten-foot circle opens onto a permanent circle elsewhere, and stays open for a single round.'),
('sp_wallofstone','Wall of Stone','Wall of Stone',5,'Utility','5th Circle','evocation',null,null,
 true,false,'120 feet','Up to 10 minutes','1 action',array['v','s','m'],'a small block of granite',
 array['druid','sorcerer','wizard'],
 'Ten panels, each 10 feet by 10 and 6 inches thick - a wall, a bridge, a ramp or a box. Each panel has AC 15 and 180 hit points. If you hold concentration the whole duration, the wall becomes PERMANENT.',
 'A wall of stone you shape as it appears, and which stays for good if you concentrate long enough.')
on conflict (key) where game_id is null do update set
  name=excluded.name, roll_name=excluded.roll_name, level=excluded.level,
  cast_type=excluded.cast_type, category=excluded.category, school=excluded.school,
  save_ability=excluded.save_ability, dice=excluded.dice,
  concentration=excluded.concentration, ritual=excluded.ritual,
  range=excluded.range, duration=excluded.duration, casting_time=excluded.casting_time,
  components=excluded.components, material=excluded.material, classes=excluded.classes,
  special_text=excluded.special_text, description=excluded.description;
